#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : Mayo_sign_with_zynq.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed May 17 11:03:00 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Mayo_sign_with_zynq.sh [-help]
# usage: Mayo_sign_with_zynq.sh [-lib_map_path]
# usage: Mayo_sign_with_zynq.sh [-noclean_files]
# usage: Mayo_sign_with_zynq.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Mayo_sign_with_zynq.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm blk_mem_gen_v8_4_4 xil_defaultlib xlconstant_v1_1_7 fifo_generator_v13_2_5 xlconcat_v2_1_4 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_bram_ctrl_v4_1_4 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Mayo_sign_with_zynq.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_BigBRAM_2_256K_0/sim/Mayo_sign_with_zynq_BigBRAM_2_256K_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_0/sim/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_BigBRAM_3_256K_0/sim/Mayo_sign_with_zynq_BigBRAM_3_256K_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_1/sim/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_1.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_1/sim/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground0_0/sim/Mayo_sign_with_zynq_Ground0_0.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground32_0/sim/Mayo_sign_with_zynq_Ground32_0.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground4_0/sim/Mayo_sign_with_zynq_Ground4_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_0/sim/Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_linear_combinat_0_0/sim/Mayo_sign_with_zynq_mayo_linear_combinat_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_MAYO_P1P1T_0_0/sim/Mayo_sign_with_zynq_MAYO_P1P1T_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_0/sim/Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_SmallBRAM_1_8K_0/sim/Mayo_sign_with_zynq_SmallBRAM_1_8K_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_2/sim/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_2.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_2/sim/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_TRNG_0_0/sources_1/ip/fifo_generator_0/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_TRNG_0_0/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_TRNG_0_0/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_TRNG_0_0/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/a179/sources_1/imports/rtl/neoTRNG.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/a179/sources_1/new/TRNG.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_TRNG_0_0/sim/Mayo_sign_with_zynq_TRNG_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconcat_0_0/sim/Mayo_sign_with_zynq_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_trng_arbiter_0_0/sim/Mayo_sign_with_zynq_mayo_trng_arbiter_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_vectors_arb_0_0/sim/Mayo_sign_with_zynq_mayo_add_vectors_arb_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_vectors_0_0/sim/Mayo_sign_with_zynq_mayo_add_vectors_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_0/sim/Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/SHA_SHAKE_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/keccak_globals.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/keccak.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/keccak_buffer.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/keccak_round.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/keccak_round_constants_gen.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/7b2a/src/MAYO_SHAKE.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_MAYO_SHAKE_1_0/sim/Mayo_sign_with_zynq_MAYO_SHAKE_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_oil_0_0/sim/Mayo_sign_with_zynq_mayo_add_oil_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_negate_0_0/sim/Mayo_sign_with_zynq_mayo_negate_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_reduce_0_0/sim/Mayo_sign_with_zynq_mayo_reduce_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_reduce_extension_0_0/sim/Mayo_sign_with_zynq_mayo_reduce_extension_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_oil_0_0/sim/Mayo_sign_with_zynq_mayo_sample_oil_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_oil_space_0_0/sim/Mayo_sign_with_zynq_mayo_sample_oil_space_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_vinegar_0_0/sim/Mayo_sign_with_zynq_mayo_sample_vinegar_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_memcpy_0_0/sim/Mayo_sign_with_zynq_memcpy_0_0.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_memcpy_1_0/sim/Mayo_sign_with_zynq_memcpy_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_processing_system7_0_0/sim/Mayo_sign_with_zynq_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/d4c9/hdl/mayo_axi_litev3_v3_S00_AXI.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ipshared/d4c9/hdl/mayo_axi_litev3_v3.vhd" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_axi_litev3_0_0/sim/Mayo_sign_with_zynq_mayo_axi_litev3_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_rst_ps7_0_100M_0/sim/Mayo_sign_with_zynq_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_1_4 $vhdlan_opts \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/c9f0/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_axi_bram_ctrl_0_0/sim/Mayo_sign_with_zynq_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xbar_0/sim/Mayo_sign_with_zynq_xbar_0.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconcat_0_1/sim/Mayo_sign_with_zynq_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconstant_0_0/sim/Mayo_sign_with_zynq_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_sign_with_zynq/ipshared/34f8/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_auto_pc_1/sim/Mayo_sign_with_zynq_auto_pc_1.v" \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_auto_pc_0/sim/Mayo_sign_with_zynq_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Mayo_sign_with_zynq/sim/Mayo_sign_with_zynq.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Mayo_sign_with_zynq xil_defaultlib.glbl -o Mayo_sign_with_zynq_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Mayo_sign_with_zynq_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Mayo_sign_with_zynq.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Mayo_sign_with_zynq_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Mayo_sign_with_zynq_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Mayo_sign_with_zynq.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Mayo_sign_with_zynq.sh [-help]\n\
Usage: Mayo_sign_with_zynq.sh [-lib_map_path]\n\
Usage: Mayo_sign_with_zynq.sh [-reset_run]\n\
Usage: Mayo_sign_with_zynq.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
