// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module computeP2_linear_combination (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        vecs_read,
        coeffs_read,
        len,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] vecs_read;
input  [7:0] coeffs_read;
input  [5:0] len;
output  [5:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [4:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ce0;
reg out_r_we0;

(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] empty_42_fu_146_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] zext_ln103_fu_175_p1;
reg   [31:0] zext_ln103_reg_262;
wire   [0:0] exitcond136_fu_157_p2;
wire   [5:0] add_ln103_fu_179_p2;
reg   [5:0] add_ln103_reg_267;
wire    ap_CS_fsm_state3;
wire   [5:0] add_ln107_fu_190_p2;
reg   [5:0] add_ln107_reg_275;
wire    ap_CS_fsm_state4;
reg   [5:0] accumulators_addr_6_reg_283;
wire   [0:0] icmp_ln107_fu_201_p2;
wire   [31:0] add_ln109_fu_207_p2;
reg   [31:0] add_ln109_reg_288;
wire    ap_CS_fsm_state5;
wire   [5:0] add_ln113_fu_212_p2;
reg   [5:0] add_ln113_reg_293;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln113_fu_218_p1;
reg   [63:0] zext_ln113_reg_298;
wire   [0:0] icmp_ln113_fu_223_p2;
wire   [31:0] accumulators_q0;
reg   [31:0] accumulators_load_reg_311;
wire    ap_CS_fsm_state8;
reg   [5:0] accumulators_address0;
reg    accumulators_ce0;
reg    accumulators_we0;
reg   [31:0] accumulators_d0;
reg   [5:0] empty_reg_102;
reg   [5:0] i_reg_113;
reg   [5:0] j_reg_124;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln103_fu_185_p2;
reg   [5:0] i_3_reg_135;
wire    ap_CS_fsm_state44;
wire   [63:0] p_cast_fu_152_p1;
wire   [63:0] zext_ln107_fu_196_p1;
wire   [7:0] mul_ln109_fu_169_p0;
wire   [7:0] mul_ln109_fu_169_p1;
wire   [15:0] mul_ln109_fu_169_p2;
wire   [5:0] grp_fu_229_p1;
wire    ap_CS_fsm_state9;
wire   [4:0] grp_fu_229_p2;
reg    grp_fu_229_ap_start;
wire    grp_fu_229_ap_done;
reg   [43:0] ap_NS_fsm;
wire   [15:0] mul_ln109_fu_169_p00;
wire   [15:0] mul_ln109_fu_169_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
end

computeP2_linear_combination_accumulators #(
    .DataWidth( 32 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(accumulators_address0),
    .ce0(accumulators_ce0),
    .we0(accumulators_we0),
    .d0(accumulators_d0),
    .q0(accumulators_q0)
);

computeP2_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(mul_ln109_fu_169_p0),
    .din1(mul_ln109_fu_169_p1),
    .dout(mul_ln109_fu_169_p2)
);

computeP2_urem_32ns_6ns_5_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 5 ))
urem_32ns_6ns_5_36_seq_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_229_ap_start),
    .done(grp_fu_229_ap_done),
    .din0(accumulators_load_reg_311),
    .din1(grp_fu_229_p1),
    .ce(1'b1),
    .dout(grp_fu_229_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond136_fu_157_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_102 <= empty_42_fu_146_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_102 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln103_fu_185_p2 == 1'd1))) begin
        i_3_reg_135 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        i_3_reg_135 <= add_ln113_reg_293;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond136_fu_157_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_113 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln107_fu_201_p2 == 1'd1))) begin
        i_reg_113 <= add_ln103_reg_267;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln103_fu_185_p2 == 1'd0))) begin
        j_reg_124 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        j_reg_124 <= add_ln107_reg_275;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln107_fu_201_p2 == 1'd0))) begin
        accumulators_addr_6_reg_283 <= zext_ln107_fu_196_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        accumulators_load_reg_311 <= accumulators_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln103_reg_267 <= add_ln103_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln107_reg_275 <= add_ln107_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln109_reg_288 <= add_ln109_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln113_reg_293 <= add_ln113_fu_212_p2;
        zext_ln113_reg_298[5 : 0] <= zext_ln113_fu_218_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond136_fu_157_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln103_reg_262[15 : 0] <= zext_ln103_fu_175_p1[15 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        accumulators_address0 = zext_ln113_fu_218_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        accumulators_address0 = accumulators_addr_6_reg_283;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        accumulators_address0 = zext_ln107_fu_196_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        accumulators_address0 = p_cast_fu_152_p1;
    end else begin
        accumulators_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        accumulators_ce0 = 1'b1;
    end else begin
        accumulators_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        accumulators_d0 = add_ln109_reg_288;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        accumulators_d0 = 32'd0;
    end else begin
        accumulators_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((exitcond136_fu_157_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        accumulators_we0 = 1'b1;
    end else begin
        accumulators_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln113_fu_223_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln113_fu_223_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_229_ap_start = 1'b1;
    end else begin
        grp_fu_229_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond136_fu_157_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln103_fu_185_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln107_fu_201_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln113_fu_223_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_179_p2 = (i_reg_113 + 6'd1);

assign add_ln107_fu_190_p2 = (j_reg_124 + 6'd1);

assign add_ln109_fu_207_p2 = (accumulators_q0 + zext_ln103_reg_262);

assign add_ln113_fu_212_p2 = (i_3_reg_135 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign empty_42_fu_146_p2 = (empty_reg_102 + 6'd1);

assign exitcond136_fu_157_p2 = ((empty_reg_102 == 6'd60) ? 1'b1 : 1'b0);

assign grp_fu_229_p1 = 32'd31;

assign icmp_ln103_fu_185_p2 = ((i_reg_113 == len) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_201_p2 = ((j_reg_124 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_223_p2 = ((i_3_reg_135 == 6'd60) ? 1'b1 : 1'b0);

assign mul_ln109_fu_169_p0 = mul_ln109_fu_169_p00;

assign mul_ln109_fu_169_p00 = vecs_read;

assign mul_ln109_fu_169_p1 = mul_ln109_fu_169_p10;

assign mul_ln109_fu_169_p10 = coeffs_read;

assign out_r_address0 = zext_ln113_reg_298;

assign out_r_d0 = grp_fu_229_p2[4:0];

assign p_cast_fu_152_p1 = empty_reg_102;

assign zext_ln103_fu_175_p1 = mul_ln109_fu_169_p2;

assign zext_ln107_fu_196_p1 = j_reg_124;

assign zext_ln113_fu_218_p1 = i_3_reg_135;

always @ (posedge ap_clk) begin
    zext_ln103_reg_262[31:16] <= 16'b0000000000000000;
    zext_ln113_reg_298[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //computeP2_linear_combination
