// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module computeP2_generic_remainder_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    ap_const_lv53_0 = 53'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] ret_18_fu_213_p1;
reg   [63:0] ret_18_reg_1003;
reg   [0:0] p_Repl2_2_reg_1011;
wire   [51:0] ret_19_fu_235_p1;
reg   [51:0] ret_19_reg_1022;
wire   [0:0] isZ_e_x_fu_239_p2;
reg   [0:0] isZ_e_x_reg_1029;
wire   [0:0] isF_e_x_fu_245_p2;
reg   [0:0] isF_e_x_reg_1033;
wire   [11:0] zext_ln169_fu_257_p1;
reg   [11:0] zext_ln169_reg_1037;
wire   [0:0] isyBx_1e_fu_267_p2;
reg   [0:0] isyBx_1e_reg_1042;
wire   [0:0] isyBx_2e_fu_283_p2;
reg   [0:0] isyBx_2e_reg_1046;
wire   [0:0] isxEy_m_fu_289_p2;
reg   [0:0] isxEy_m_reg_1050;
wire   [0:0] isyBx_m_fu_295_p2;
reg   [0:0] isyBx_m_reg_1054;
wire   [0:0] and_ln414_fu_313_p2;
reg   [0:0] and_ln414_reg_1058;
wire   [0:0] icmp_ln844_fu_323_p2;
reg   [0:0] icmp_ln844_reg_1062;
wire   [5:0] LZ_V_fu_355_p1;
reg   [5:0] LZ_V_reg_1066;
wire   [6:0] LZ_V_cast_fu_359_p1;
reg   [6:0] LZ_V_cast_reg_1072;
wire   [0:0] icmp_ln368_fu_369_p2;
reg   [0:0] icmp_ln368_reg_1077;
wire   [5:0] trunc_ln368_fu_375_p1;
reg   [5:0] trunc_ln368_reg_1085;
wire   [52:0] p_Result_44_fu_379_p3;
wire    ap_CS_fsm_state2;
wire   [63:0] p_Result_39_fu_395_p3;
wire    ap_CS_fsm_state3;
wire   [53:0] shl_ln368_fu_462_p2;
reg   [53:0] shl_ln368_reg_1103;
wire    ap_CS_fsm_state4;
wire   [53:0] and_ln368_fu_480_p2;
reg   [53:0] and_ln368_reg_1109;
wire  signed [11:0] sext_ln1301_1_fu_491_p1;
wire    ap_CS_fsm_state5;
wire   [52:0] trunc_ln345_fu_542_p1;
wire  signed [11:0] ret_20_fu_546_p2;
reg  signed [11:0] ret_20_reg_1124;
wire    ap_CS_fsm_state6;
wire  signed [12:0] sext_ln1301_2_fu_552_p1;
wire   [53:0] zext_ln368_fu_556_p1;
wire   [11:0] loop_V_1_fu_560_p2;
wire    ap_CS_fsm_state7;
wire   [53:0] r_sh_V_7_fu_604_p3;
wire   [0:0] icmp_ln832_fu_566_p2;
wire   [12:0] i_V_3_fu_612_p3;
wire   [0:0] and_ln503_fu_626_p2;
reg   [0:0] and_ln503_reg_1157;
wire   [53:0] r_sh_V_4_fu_638_p3;
reg   [53:0] r_sh_V_4_reg_1162;
wire   [0:0] icmp_ln832_1_fu_646_p2;
reg   [0:0] icmp_ln832_1_reg_1173;
wire   [11:0] trunc_ln645_fu_651_p1;
reg   [11:0] trunc_ln645_reg_1177;
wire    ap_CS_fsm_state8;
wire   [53:0] r_sh_V_fu_768_p3;
reg   [53:0] r_sh_V_reg_1182;
wire   [0:0] s_r_V_3_fu_798_p3;
reg   [0:0] s_r_V_3_reg_1190;
wire   [0:0] icmp_ln824_5_fu_805_p2;
reg   [0:0] icmp_ln824_5_reg_1196;
wire    ap_CS_fsm_state9;
wire   [53:0] r_4_fu_896_p3;
reg   [53:0] r_4_reg_1200;
wire   [0:0] icmp_ln836_2_fu_904_p2;
reg   [0:0] icmp_ln836_2_reg_1206;
wire   [10:0] fz_exp_V_fu_916_p2;
reg   [10:0] fz_exp_V_reg_1212;
wire   [12:0] n_V_fu_926_p2;
reg   [12:0] n_V_reg_1217;
wire   [63:0] p_Result_45_fu_932_p3;
wire   [63:0] p_Result_38_fu_981_p4;
wire    ap_CS_fsm_state11;
wire   [63:0] p_Result_37_fu_989_p3;
wire    ap_CS_fsm_state12;
wire   [63:0] p_Result_36_fu_996_p3;
wire    ap_CS_fsm_state13;
reg   [52:0] ap_mx_V_reg_136;
reg   [11:0] ix_0_in_reg_145;
reg   [11:0] loop_V_reg_154;
reg   [12:0] i_V_1_reg_165;
reg   [53:0] r_sh_V_3_reg_175;
reg   [63:0] ap_phi_mux_retval_0_in_phi_fu_187_p18;
reg   [63:0] retval_0_in_reg_184;
wire   [63:0] p_Result_47_fu_967_p4;
wire    ap_CS_fsm_state10;
wire   [10:0] ret_10_fu_225_p4;
wire   [11:0] ret_fu_261_p2;
wire   [10:0] tmp_4_fu_273_p4;
wire   [0:0] icmp_ln824_fu_251_p2;
wire   [52:0] p_Result_35_fu_301_p5;
wire   [51:0] trunc_ln628_fu_319_p1;
reg   [51:0] p_Result_s_fu_329_p4;
wire   [63:0] p_Result_40_fu_339_p3;
reg   [63:0] tmp_7_fu_347_p3;
wire   [6:0] add_ln461_fu_363_p2;
wire   [11:0] tmp_fu_386_p4;
wire   [51:0] zext_ln628_fu_403_p1;
wire   [51:0] lshr_ln628_fu_406_p2;
wire   [51:0] p_Result_41_fu_412_p2;
wire   [5:0] sub_ln368_fu_421_p2;
wire   [5:0] sub_ln368_1_fu_438_p2;
wire   [5:0] select_ln368_1_fu_432_p3;
wire   [5:0] select_ln368_fu_426_p3;
wire   [5:0] select_ln368_2_fu_443_p3;
wire   [53:0] zext_ln169_1_fu_417_p1;
wire   [53:0] zext_ln368_1_fu_450_p1;
wire   [53:0] zext_ln368_2_fu_454_p1;
wire   [53:0] zext_ln368_3_fu_458_p1;
wire   [53:0] shl_ln368_1_fu_468_p2;
wire   [53:0] lshr_ln368_fu_474_p2;
wire   [6:0] p_neg_fu_486_p2;
reg   [53:0] tmp_6_fu_495_p4;
wire   [53:0] select_ln368_3_fu_504_p3;
wire   [5:0] sub_ln345_fu_515_p2;
wire   [53:0] zext_ln345_fu_520_p1;
wire   [53:0] lshr_ln345_fu_524_p2;
wire   [53:0] p_Result_42_fu_510_p2;
wire   [53:0] xor_ln345_fu_530_p2;
wire   [53:0] p_Result_43_fu_536_p2;
wire   [53:0] r_3_fu_584_p2;
wire   [0:0] grp_fu_207_p2;
wire   [53:0] r_sh_V_5_fu_590_p2;
wire   [0:0] icmp_ln840_fu_572_p2;
wire   [53:0] select_ln497_fu_596_p3;
wire   [12:0] i_V_2_fu_578_p2;
wire   [0:0] icmp_ln824_3_fu_620_p2;
wire   [53:0] r_sh_V_2_fu_632_p2;
wire   [53:0] r_fu_655_p2;
wire   [0:0] s_r_V_fu_672_p2;
wire   [0:0] icmp_ln832_2_fu_660_p2;
wire   [0:0] icmp_ln824_4_fu_666_p2;
wire   [0:0] xor_ln832_fu_703_p2;
wire   [0:0] and_ln824_fu_709_p2;
wire   [0:0] icmp_ln824_8_fu_722_p2;
wire   [0:0] icmp_ln832_3_fu_683_p2;
wire   [0:0] and_ln832_fu_728_p2;
wire   [53:0] r_sh_V_8_fu_688_p2;
wire   [53:0] r_sh_V_10_fu_715_p3;
wire   [0:0] icmp_ln840_1_fu_693_p2;
wire   [0:0] xor_ln832_1_fu_742_p2;
wire   [0:0] and_ln840_fu_748_p2;
wire   [0:0] and_ln840_1_fu_754_p2;
wire   [53:0] r_sh_V_9_fu_698_p2;
wire   [53:0] r_sh_V_11_fu_734_p3;
wire   [53:0] r_sh_V_12_fu_760_p3;
wire   [0:0] select_ln517_fu_677_p3;
wire   [0:0] select_ln824_fu_775_p3;
wire   [0:0] select_ln832_fu_782_p3;
wire   [0:0] select_ln840_fu_790_p3;
reg   [53:0] p_Result_5_fu_810_p4;
wire   [63:0] p_Result_46_fu_819_p3;
reg   [63:0] tmp_8_fu_827_p3;
wire   [31:0] trunc_ln1010_fu_835_p1;
wire   [11:0] trunc_ln646_fu_845_p1;
wire   [11:0] iy_V_fu_849_p2;
wire   [52:0] lshr_ln_fu_874_p4;
wire   [31:0] add_ln534_fu_839_p2;
wire   [53:0] zext_ln1451_fu_887_p1;
wire   [0:0] icmp_ln1451_fu_868_p2;
wire   [53:0] zext_ln1451_1_fu_883_p1;
wire   [53:0] shl_ln1451_fu_891_p2;
wire  signed [11:0] iy_V_1_fu_863_p2;
wire   [10:0] trunc_ln645_1_fu_855_p1;
wire   [10:0] add_ln167_fu_910_p2;
wire   [10:0] trunc_ln645_2_fu_859_p1;
wire  signed [12:0] sext_ln1301_fu_922_p1;
wire   [53:0] zext_ln803_fu_939_p1;
wire   [53:0] ap_mx_2_V_fu_942_p2;
wire   [51:0] trunc_ln836_fu_953_p1;
wire   [51:0] trunc_ln836_1_fu_956_p1;
wire   [10:0] ret_15_fu_947_p3;
wire   [51:0] fz_sig_V_fu_960_p3;
wire   [63:0] bitcast_ln521_fu_977_p1;
reg   [63:0] ap_return_preg;
reg   [12:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_return_preg = 64'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_preg <= bitcast_ln521_fu_977_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_mx_V_reg_136 <= p_Result_44_fu_379_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_mx_V_reg_136 <= trunc_ln345_fu_542_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln832_fu_566_p2 == 1'd0))) begin
        i_V_1_reg_165 <= i_V_3_fu_612_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_V_1_reg_165 <= sext_ln1301_2_fu_552_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ix_0_in_reg_145 <= zext_ln169_reg_1037;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        ix_0_in_reg_145 <= sext_ln1301_1_fu_491_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln832_fu_566_p2 == 1'd0))) begin
        loop_V_reg_154 <= loop_V_1_fu_560_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        loop_V_reg_154 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln832_fu_566_p2 == 1'd0))) begin
        r_sh_V_3_reg_175 <= r_sh_V_7_fu_604_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        r_sh_V_3_reg_175 <= zext_ln368_fu_556_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln832_1_reg_1173 == 1'd1))) begin
        retval_0_in_reg_184 <= ret_18_reg_1003;
    end else if ((((1'd0 == and_ln414_fu_313_p2) & (isyBx_m_fu_295_p2 == 1'd1) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        retval_0_in_reg_184 <= ret_18_fu_213_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        retval_0_in_reg_184 <= p_Result_39_fu_395_p3;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((((icmp_ln844_reg_1062 == 1'd0) & (1'd0 == and_ln414_reg_1058) & (isyBx_2e_reg_1046 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (isZ_e_x_reg_1029 == 1'd1) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0)) | ((1'd0 == and_ln414_reg_1058) & (isyBx_m_reg_1054 == 1'd0) & (isxEy_m_reg_1050 == 1'd0) & (isyBx_2e_reg_1046 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (isZ_e_x_reg_1029 == 1'd0) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0))) | ((1'd0 == and_ln414_reg_1058) & (isyBx_2e_reg_1046 == 1'd0) & (isyBx_1e_reg_1042 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0))))) begin
        retval_0_in_reg_184 <= p_Result_47_fu_967_p4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln824_5_fu_805_p2 == 1'd1))) begin
        retval_0_in_reg_184 <= p_Result_45_fu_932_p3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        retval_0_in_reg_184 <= p_Result_38_fu_981_p4;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        retval_0_in_reg_184 <= p_Result_37_fu_989_p3;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        retval_0_in_reg_184 <= p_Result_36_fu_996_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((icmp_ln844_fu_323_p2 == 1'd0) & (1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1))))) begin
        LZ_V_cast_reg_1072[5 : 0] <= LZ_V_cast_fu_359_p1[5 : 0];
        LZ_V_reg_1066 <= LZ_V_fu_355_p1;
        icmp_ln368_reg_1077 <= icmp_ln368_fu_369_p2;
        trunc_ln368_reg_1085 <= trunc_ln368_fu_375_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        and_ln368_reg_1109 <= and_ln368_fu_480_p2;
        shl_ln368_reg_1103 <= shl_ln368_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((isF_e_x_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln414_reg_1058 <= and_ln414_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln832_fu_566_p2 == 1'd1))) begin
        and_ln503_reg_1157 <= and_ln503_fu_626_p2;
        icmp_ln832_1_reg_1173 <= icmp_ln832_1_fu_646_p2;
        r_sh_V_4_reg_1162 <= r_sh_V_4_fu_638_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln824_5_fu_805_p2 == 1'd0))) begin
        fz_exp_V_reg_1212 <= fz_exp_V_fu_916_p2;
        icmp_ln836_2_reg_1206 <= icmp_ln836_2_fu_904_p2;
        n_V_reg_1217 <= n_V_fu_926_p2;
        r_4_reg_1200 <= r_4_fu_896_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln824_5_reg_1196 <= icmp_ln824_5_fu_805_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln844_reg_1062 <= icmp_ln844_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        isF_e_x_reg_1033 <= isF_e_x_fu_245_p2;
        isZ_e_x_reg_1029 <= isZ_e_x_fu_239_p2;
        isxEy_m_reg_1050 <= isxEy_m_fu_289_p2;
        isyBx_1e_reg_1042 <= isyBx_1e_fu_267_p2;
        isyBx_2e_reg_1046 <= isyBx_2e_fu_283_p2;
        isyBx_m_reg_1054 <= isyBx_m_fu_295_p2;
        p_Repl2_2_reg_1011 <= ret_18_fu_213_p1[32'd63];
        ret_18_reg_1003 <= ret_18_fu_213_p1;
        ret_19_reg_1022 <= ret_19_fu_235_p1;
        zext_ln169_reg_1037[10 : 0] <= zext_ln169_fu_257_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln832_1_reg_1173 == 1'd0))) begin
        r_sh_V_reg_1182 <= r_sh_V_fu_768_p3;
        s_r_V_3_reg_1190 <= s_r_V_3_fu_798_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ret_20_reg_1124 <= ret_20_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln645_reg_1177 <= trunc_ln645_fu_651_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & ((((icmp_ln844_reg_1062 == 1'd0) & (1'd0 == and_ln414_reg_1058) & (isyBx_2e_reg_1046 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (isZ_e_x_reg_1029 == 1'd1) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0)) | ((1'd0 == and_ln414_reg_1058) & (isyBx_m_reg_1054 == 1'd0) & (isxEy_m_reg_1050 == 1'd0) & (isyBx_2e_reg_1046 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (isZ_e_x_reg_1029 == 1'd0) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0))) | ((1'd0 == and_ln414_reg_1058) & (isyBx_2e_reg_1046 == 1'd0) & (isyBx_1e_reg_1042 == 1'd0) & (isF_e_x_reg_1033 == 1'd0) & (icmp_ln824_5_reg_1196 == 1'd0) & (icmp_ln832_1_reg_1173 == 1'd0))))) begin
        ap_phi_mux_retval_0_in_phi_fu_187_p18 = p_Result_47_fu_967_p4;
    end else begin
        ap_phi_mux_retval_0_in_phi_fu_187_p18 = retval_0_in_reg_184;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return = bitcast_ln521_fu_977_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln844_fu_323_p2 == 1'd1) & (1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'd0 == and_ln414_fu_313_p2) & (isyBx_m_fu_295_p2 == 1'd0) & (isxEy_m_fu_289_p2 == 1'd1) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (((icmp_ln844_fu_323_p2 == 1'd0) & (1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1)) | ((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (((1'd0 == and_ln414_fu_313_p2) & (isyBx_m_fu_295_p2 == 1'd0) & (isxEy_m_fu_289_p2 == 1'd0) & (isyBx_2e_fu_283_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd0)) | ((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd0) & (isyBx_1e_fu_267_p2 == 1'd0) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (((1'd0 == and_ln414_fu_313_p2) & (isyBx_m_fu_295_p2 == 1'd1) & (isyBx_1e_fu_267_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0) & (isZ_e_x_fu_239_p2 == 1'd0)) | ((1'd0 == and_ln414_fu_313_p2) & (isyBx_2e_fu_283_p2 == 1'd1) & (isF_e_x_fu_245_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((1'd1 == and_ln414_fu_313_p2) & (isF_e_x_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((isF_e_x_fu_245_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln832_fu_566_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln832_1_reg_1173 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LZ_V_cast_fu_359_p1 = LZ_V_fu_355_p1;

assign LZ_V_fu_355_p1 = tmp_7_fu_347_p3[5:0];

assign add_ln167_fu_910_p2 = (trunc_ln645_1_fu_855_p1 + 11'd1023);

assign add_ln461_fu_363_p2 = (LZ_V_cast_fu_359_p1 + 7'd1);

assign add_ln534_fu_839_p2 = ($signed(trunc_ln1010_fu_835_p1) + $signed(32'd4294967295));

assign and_ln368_fu_480_p2 = (shl_ln368_1_fu_468_p2 & lshr_ln368_fu_474_p2);

assign and_ln414_fu_313_p2 = (isxEy_m_fu_289_p2 & icmp_ln824_fu_251_p2);

assign and_ln503_fu_626_p2 = (icmp_ln824_3_fu_620_p2 & grp_fu_207_p2);

assign and_ln824_fu_709_p2 = (xor_ln832_fu_703_p2 & icmp_ln824_4_fu_666_p2);

assign and_ln832_fu_728_p2 = (icmp_ln832_3_fu_683_p2 & icmp_ln824_8_fu_722_p2);

assign and_ln840_1_fu_754_p2 = (icmp_ln824_8_fu_722_p2 & and_ln840_fu_748_p2);

assign and_ln840_fu_748_p2 = (xor_ln832_1_fu_742_p2 & icmp_ln840_1_fu_693_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_mx_2_V_fu_942_p2 = r_4_reg_1200 >> zext_ln803_fu_939_p1;

assign bitcast_ln521_fu_977_p1 = ap_phi_mux_retval_0_in_phi_fu_187_p18;

assign fz_exp_V_fu_916_p2 = (add_ln167_fu_910_p2 + trunc_ln645_2_fu_859_p1);

assign fz_sig_V_fu_960_p3 = ((icmp_ln836_2_reg_1206[0:0] == 1'b1) ? trunc_ln836_fu_953_p1 : trunc_ln836_1_fu_956_p1);

assign grp_fu_207_p2 = ((r_sh_V_3_reg_175 > 54'd8725724278030335) ? 1'b1 : 1'b0);

assign i_V_2_fu_578_p2 = ($signed(i_V_1_reg_165) + $signed(13'd8191));

assign i_V_3_fu_612_p3 = ((icmp_ln840_fu_572_p2[0:0] == 1'b1) ? i_V_2_fu_578_p2 : i_V_1_reg_165);

assign icmp_ln1451_fu_868_p2 = ((trunc_ln1010_fu_835_p1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln368_fu_369_p2 = ((add_ln461_fu_363_p2 > 7'd52) ? 1'b1 : 1'b0);

assign icmp_ln824_3_fu_620_p2 = ((i_V_1_reg_165 == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln824_4_fu_666_p2 = ((r_fu_655_p2 == 54'd8725724278030336) ? 1'b1 : 1'b0);

assign icmp_ln824_5_fu_805_p2 = ((r_sh_V_reg_1182 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln824_8_fu_722_p2 = ((r_fu_655_p2 > 54'd8725724278030336) ? 1'b1 : 1'b0);

assign icmp_ln824_fu_251_p2 = ((ret_10_fu_225_p4 == 11'd1027) ? 1'b1 : 1'b0);

assign icmp_ln832_1_fu_646_p2 = (($signed(ret_20_reg_1124) < $signed(12'd4095)) ? 1'b1 : 1'b0);

assign icmp_ln832_2_fu_660_p2 = ((r_fu_655_p2 < 54'd8725724278030336) ? 1'b1 : 1'b0);

assign icmp_ln832_3_fu_683_p2 = ((r_sh_V_4_reg_1162 < 54'd8725724278030336) ? 1'b1 : 1'b0);

assign icmp_ln832_fu_566_p2 = ((loop_V_reg_154 == 12'd2098) ? 1'b1 : 1'b0);

assign icmp_ln836_2_fu_904_p2 = (($signed(iy_V_1_fu_863_p2) > $signed(12'd3073)) ? 1'b1 : 1'b0);

assign icmp_ln840_1_fu_693_p2 = ((r_sh_V_4_reg_1162 > 54'd8725724278030336) ? 1'b1 : 1'b0);

assign icmp_ln840_fu_572_p2 = (($signed(i_V_1_reg_165) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln844_fu_323_p2 = ((trunc_ln628_fu_319_p1 < 52'd4222124650659841) ? 1'b1 : 1'b0);

assign isF_e_x_fu_245_p2 = ((ret_10_fu_225_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign isZ_e_x_fu_239_p2 = ((ret_10_fu_225_p4 == 11'd0) ? 1'b1 : 1'b0);

assign isxEy_m_fu_289_p2 = ((ret_19_fu_235_p1 == 52'd4222124650659840) ? 1'b1 : 1'b0);

assign isyBx_1e_fu_267_p2 = ((ret_fu_261_p2 == 12'd1) ? 1'b1 : 1'b0);

assign isyBx_2e_fu_283_p2 = (($signed(tmp_4_fu_273_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign isyBx_m_fu_295_p2 = ((ret_19_fu_235_p1 < 52'd4222124650659840) ? 1'b1 : 1'b0);

assign iy_V_1_fu_863_p2 = (iy_V_fu_849_p2 + trunc_ln645_reg_1177);

assign iy_V_fu_849_p2 = (12'd5 - trunc_ln646_fu_845_p1);

assign loop_V_1_fu_560_p2 = (loop_V_reg_154 + 12'd1);

assign lshr_ln345_fu_524_p2 = 54'd18014398509481983 >> zext_ln345_fu_520_p1;

assign lshr_ln368_fu_474_p2 = 54'd18014398509481983 >> zext_ln368_3_fu_458_p1;

assign lshr_ln628_fu_406_p2 = 52'd4503599627370495 >> zext_ln628_fu_403_p1;

assign lshr_ln_fu_874_p4 = {{r_sh_V_reg_1182[53:1]}};

assign n_V_fu_926_p2 = ($signed(13'd7170) - $signed(sext_ln1301_fu_922_p1));

assign p_Result_35_fu_301_p5 = {{ret_19_fu_235_p1}, {ap_const_lv53_0[0:0]}};

assign p_Result_36_fu_996_p3 = {{p_Repl2_2_reg_1011}, {63'd9223372036854775807}};

assign p_Result_37_fu_989_p3 = {{p_Repl2_2_reg_1011}, {63'd0}};

assign p_Result_38_fu_981_p4 = {{{p_Repl2_2_reg_1011}, {11'd0}}, {ret_19_reg_1022}};

assign p_Result_39_fu_395_p3 = {{tmp_fu_386_p4}, {52'd4222124650659840}};

assign p_Result_40_fu_339_p3 = {{12'd4095}, {p_Result_s_fu_329_p4}};

assign p_Result_41_fu_412_p2 = (ret_19_reg_1022 & lshr_ln628_fu_406_p2);

assign p_Result_42_fu_510_p2 = (select_ln368_3_fu_504_p3 & and_ln368_reg_1109);

assign p_Result_43_fu_536_p2 = (xor_ln345_fu_530_p2 & p_Result_42_fu_510_p2);

assign p_Result_44_fu_379_p3 = {{1'd1}, {ret_19_reg_1022}};

assign p_Result_45_fu_932_p3 = {{s_r_V_3_reg_1190}, {63'd0}};

assign p_Result_46_fu_819_p3 = {{10'd1023}, {p_Result_5_fu_810_p4}};

assign p_Result_47_fu_967_p4 = {{{s_r_V_3_reg_1190}, {ret_15_fu_947_p3}}, {fz_sig_V_fu_960_p3}};

integer ap_tvar_int_0;

always @ (r_sh_V_reg_1182) begin
    for (ap_tvar_int_0 = 54 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 53 - 0) begin
            p_Result_5_fu_810_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_5_fu_810_p4[ap_tvar_int_0] = r_sh_V_reg_1182[53 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (ret_18_fu_213_p1) begin
    for (ap_tvar_int_1 = 52 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 51 - 0) begin
            p_Result_s_fu_329_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_329_p4[ap_tvar_int_1] = ret_18_fu_213_p1[51 - ap_tvar_int_1];
        end
    end
end

assign p_neg_fu_486_p2 = (7'd0 - LZ_V_cast_reg_1072);

assign r_3_fu_584_p2 = r_sh_V_3_reg_175 << 54'd1;

assign r_4_fu_896_p3 = ((icmp_ln1451_fu_868_p2[0:0] == 1'b1) ? zext_ln1451_1_fu_883_p1 : shl_ln1451_fu_891_p2);

assign r_fu_655_p2 = r_sh_V_4_reg_1162 << 54'd1;

assign r_sh_V_10_fu_715_p3 = ((and_ln824_fu_709_p2[0:0] == 1'b1) ? r_sh_V_4_reg_1162 : 54'd8725724278030336);

assign r_sh_V_11_fu_734_p3 = ((and_ln832_fu_728_p2[0:0] == 1'b1) ? r_sh_V_8_fu_688_p2 : r_sh_V_10_fu_715_p3);

assign r_sh_V_12_fu_760_p3 = ((and_ln840_1_fu_754_p2[0:0] == 1'b1) ? r_sh_V_9_fu_698_p2 : r_sh_V_11_fu_734_p3);

assign r_sh_V_2_fu_632_p2 = ($signed(r_sh_V_3_reg_175) + $signed(54'd9288674231451648));

assign r_sh_V_4_fu_638_p3 = ((and_ln503_fu_626_p2[0:0] == 1'b1) ? r_sh_V_2_fu_632_p2 : r_sh_V_3_reg_175);

assign r_sh_V_5_fu_590_p2 = (r_3_fu_584_p2 + 54'd562949953421312);

assign r_sh_V_7_fu_604_p3 = ((icmp_ln840_fu_572_p2[0:0] == 1'b1) ? select_ln497_fu_596_p3 : r_sh_V_3_reg_175);

assign r_sh_V_8_fu_688_p2 = (54'd8725724278030336 - r_sh_V_4_reg_1162);

assign r_sh_V_9_fu_698_p2 = ($signed(54'd17451448556060672) - $signed(r_sh_V_4_reg_1162));

assign r_sh_V_fu_768_p3 = ((icmp_ln832_2_fu_660_p2[0:0] == 1'b1) ? r_sh_V_4_reg_1162 : r_sh_V_12_fu_760_p3);

assign ret_10_fu_225_p4 = {{ret_18_fu_213_p1[62:52]}};

assign ret_15_fu_947_p3 = ((icmp_ln836_2_reg_1206[0:0] == 1'b1) ? fz_exp_V_reg_1212 : 11'd0);

assign ret_18_fu_213_p1 = x;

assign ret_19_fu_235_p1 = ret_18_fu_213_p1[51:0];

assign ret_20_fu_546_p2 = ($signed(ix_0_in_reg_145) + $signed(12'd3069));

assign ret_fu_261_p2 = (12'd1027 - zext_ln169_fu_257_p1);

assign s_r_V_3_fu_798_p3 = ((icmp_ln832_2_fu_660_p2[0:0] == 1'b1) ? p_Repl2_2_reg_1011 : select_ln840_fu_790_p3);

assign s_r_V_fu_672_p2 = (p_Repl2_2_reg_1011 ^ 1'd1);

assign select_ln368_1_fu_432_p3 = ((icmp_ln368_reg_1077[0:0] == 1'b1) ? sub_ln368_fu_421_p2 : trunc_ln368_reg_1085);

assign select_ln368_2_fu_443_p3 = ((icmp_ln368_reg_1077[0:0] == 1'b1) ? sub_ln368_1_fu_438_p2 : 6'd1);

assign select_ln368_3_fu_504_p3 = ((icmp_ln368_reg_1077[0:0] == 1'b1) ? tmp_6_fu_495_p4 : shl_ln368_reg_1103);

assign select_ln368_fu_426_p3 = ((icmp_ln368_reg_1077[0:0] == 1'b1) ? 6'd52 : trunc_ln368_reg_1085);

assign select_ln497_fu_596_p3 = ((grp_fu_207_p2[0:0] == 1'b1) ? r_sh_V_5_fu_590_p2 : r_3_fu_584_p2);

assign select_ln517_fu_677_p3 = ((and_ln503_reg_1157[0:0] == 1'b1) ? s_r_V_fu_672_p2 : p_Repl2_2_reg_1011);

assign select_ln824_fu_775_p3 = ((and_ln824_fu_709_p2[0:0] == 1'b1) ? select_ln517_fu_677_p3 : p_Repl2_2_reg_1011);

assign select_ln832_fu_782_p3 = ((and_ln832_fu_728_p2[0:0] == 1'b1) ? s_r_V_fu_672_p2 : select_ln824_fu_775_p3);

assign select_ln840_fu_790_p3 = ((and_ln840_1_fu_754_p2[0:0] == 1'b1) ? s_r_V_fu_672_p2 : select_ln832_fu_782_p3);

assign sext_ln1301_1_fu_491_p1 = $signed(p_neg_fu_486_p2);

assign sext_ln1301_2_fu_552_p1 = ret_20_fu_546_p2;

assign sext_ln1301_fu_922_p1 = iy_V_1_fu_863_p2;

assign shl_ln1451_fu_891_p2 = r_sh_V_reg_1182 << zext_ln1451_fu_887_p1;

assign shl_ln368_1_fu_468_p2 = 54'd18014398509481983 << zext_ln368_2_fu_454_p1;

assign shl_ln368_fu_462_p2 = zext_ln169_1_fu_417_p1 << zext_ln368_1_fu_450_p1;

assign sub_ln345_fu_515_p2 = ($signed(6'd53) - $signed(LZ_V_reg_1066));

assign sub_ln368_1_fu_438_p2 = ($signed(6'd53) - $signed(trunc_ln368_reg_1085));

assign sub_ln368_fu_421_p2 = ($signed(6'd53) - $signed(trunc_ln368_reg_1085));

assign tmp_4_fu_273_p4 = {{ret_fu_261_p2[11:1]}};

integer ap_tvar_int_2;

always @ (shl_ln368_reg_1103) begin
    for (ap_tvar_int_2 = 54 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 53 - 0) begin
            tmp_6_fu_495_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_6_fu_495_p4[ap_tvar_int_2] = shl_ln368_reg_1103[53 - ap_tvar_int_2];
        end
    end
end


always @ (p_Result_40_fu_339_p3) begin
    if (p_Result_40_fu_339_p3[0] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd0;
    end else if (p_Result_40_fu_339_p3[1] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd1;
    end else if (p_Result_40_fu_339_p3[2] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd2;
    end else if (p_Result_40_fu_339_p3[3] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd3;
    end else if (p_Result_40_fu_339_p3[4] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd4;
    end else if (p_Result_40_fu_339_p3[5] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd5;
    end else if (p_Result_40_fu_339_p3[6] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd6;
    end else if (p_Result_40_fu_339_p3[7] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd7;
    end else if (p_Result_40_fu_339_p3[8] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd8;
    end else if (p_Result_40_fu_339_p3[9] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd9;
    end else if (p_Result_40_fu_339_p3[10] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd10;
    end else if (p_Result_40_fu_339_p3[11] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd11;
    end else if (p_Result_40_fu_339_p3[12] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd12;
    end else if (p_Result_40_fu_339_p3[13] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd13;
    end else if (p_Result_40_fu_339_p3[14] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd14;
    end else if (p_Result_40_fu_339_p3[15] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd15;
    end else if (p_Result_40_fu_339_p3[16] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd16;
    end else if (p_Result_40_fu_339_p3[17] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd17;
    end else if (p_Result_40_fu_339_p3[18] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd18;
    end else if (p_Result_40_fu_339_p3[19] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd19;
    end else if (p_Result_40_fu_339_p3[20] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd20;
    end else if (p_Result_40_fu_339_p3[21] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd21;
    end else if (p_Result_40_fu_339_p3[22] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd22;
    end else if (p_Result_40_fu_339_p3[23] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd23;
    end else if (p_Result_40_fu_339_p3[24] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd24;
    end else if (p_Result_40_fu_339_p3[25] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd25;
    end else if (p_Result_40_fu_339_p3[26] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd26;
    end else if (p_Result_40_fu_339_p3[27] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd27;
    end else if (p_Result_40_fu_339_p3[28] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd28;
    end else if (p_Result_40_fu_339_p3[29] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd29;
    end else if (p_Result_40_fu_339_p3[30] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd30;
    end else if (p_Result_40_fu_339_p3[31] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd31;
    end else if (p_Result_40_fu_339_p3[32] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd32;
    end else if (p_Result_40_fu_339_p3[33] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd33;
    end else if (p_Result_40_fu_339_p3[34] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd34;
    end else if (p_Result_40_fu_339_p3[35] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd35;
    end else if (p_Result_40_fu_339_p3[36] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd36;
    end else if (p_Result_40_fu_339_p3[37] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd37;
    end else if (p_Result_40_fu_339_p3[38] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd38;
    end else if (p_Result_40_fu_339_p3[39] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd39;
    end else if (p_Result_40_fu_339_p3[40] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd40;
    end else if (p_Result_40_fu_339_p3[41] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd41;
    end else if (p_Result_40_fu_339_p3[42] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd42;
    end else if (p_Result_40_fu_339_p3[43] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd43;
    end else if (p_Result_40_fu_339_p3[44] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd44;
    end else if (p_Result_40_fu_339_p3[45] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd45;
    end else if (p_Result_40_fu_339_p3[46] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd46;
    end else if (p_Result_40_fu_339_p3[47] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd47;
    end else if (p_Result_40_fu_339_p3[48] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd48;
    end else if (p_Result_40_fu_339_p3[49] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd49;
    end else if (p_Result_40_fu_339_p3[50] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd50;
    end else if (p_Result_40_fu_339_p3[51] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd51;
    end else if (p_Result_40_fu_339_p3[52] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd52;
    end else if (p_Result_40_fu_339_p3[53] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd53;
    end else if (p_Result_40_fu_339_p3[54] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd54;
    end else if (p_Result_40_fu_339_p3[55] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd55;
    end else if (p_Result_40_fu_339_p3[56] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd56;
    end else if (p_Result_40_fu_339_p3[57] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd57;
    end else if (p_Result_40_fu_339_p3[58] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd58;
    end else if (p_Result_40_fu_339_p3[59] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd59;
    end else if (p_Result_40_fu_339_p3[60] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd60;
    end else if (p_Result_40_fu_339_p3[61] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd61;
    end else if (p_Result_40_fu_339_p3[62] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd62;
    end else if (p_Result_40_fu_339_p3[63] == 1'b1) begin
        tmp_7_fu_347_p3 = 64'd63;
    end else begin
        tmp_7_fu_347_p3 = 64'd64;
    end
end


always @ (p_Result_46_fu_819_p3) begin
    if (p_Result_46_fu_819_p3[0] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd0;
    end else if (p_Result_46_fu_819_p3[1] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd1;
    end else if (p_Result_46_fu_819_p3[2] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd2;
    end else if (p_Result_46_fu_819_p3[3] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd3;
    end else if (p_Result_46_fu_819_p3[4] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd4;
    end else if (p_Result_46_fu_819_p3[5] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd5;
    end else if (p_Result_46_fu_819_p3[6] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd6;
    end else if (p_Result_46_fu_819_p3[7] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd7;
    end else if (p_Result_46_fu_819_p3[8] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd8;
    end else if (p_Result_46_fu_819_p3[9] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd9;
    end else if (p_Result_46_fu_819_p3[10] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd10;
    end else if (p_Result_46_fu_819_p3[11] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd11;
    end else if (p_Result_46_fu_819_p3[12] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd12;
    end else if (p_Result_46_fu_819_p3[13] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd13;
    end else if (p_Result_46_fu_819_p3[14] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd14;
    end else if (p_Result_46_fu_819_p3[15] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd15;
    end else if (p_Result_46_fu_819_p3[16] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd16;
    end else if (p_Result_46_fu_819_p3[17] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd17;
    end else if (p_Result_46_fu_819_p3[18] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd18;
    end else if (p_Result_46_fu_819_p3[19] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd19;
    end else if (p_Result_46_fu_819_p3[20] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd20;
    end else if (p_Result_46_fu_819_p3[21] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd21;
    end else if (p_Result_46_fu_819_p3[22] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd22;
    end else if (p_Result_46_fu_819_p3[23] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd23;
    end else if (p_Result_46_fu_819_p3[24] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd24;
    end else if (p_Result_46_fu_819_p3[25] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd25;
    end else if (p_Result_46_fu_819_p3[26] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd26;
    end else if (p_Result_46_fu_819_p3[27] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd27;
    end else if (p_Result_46_fu_819_p3[28] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd28;
    end else if (p_Result_46_fu_819_p3[29] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd29;
    end else if (p_Result_46_fu_819_p3[30] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd30;
    end else if (p_Result_46_fu_819_p3[31] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd31;
    end else if (p_Result_46_fu_819_p3[32] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd32;
    end else if (p_Result_46_fu_819_p3[33] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd33;
    end else if (p_Result_46_fu_819_p3[34] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd34;
    end else if (p_Result_46_fu_819_p3[35] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd35;
    end else if (p_Result_46_fu_819_p3[36] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd36;
    end else if (p_Result_46_fu_819_p3[37] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd37;
    end else if (p_Result_46_fu_819_p3[38] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd38;
    end else if (p_Result_46_fu_819_p3[39] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd39;
    end else if (p_Result_46_fu_819_p3[40] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd40;
    end else if (p_Result_46_fu_819_p3[41] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd41;
    end else if (p_Result_46_fu_819_p3[42] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd42;
    end else if (p_Result_46_fu_819_p3[43] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd43;
    end else if (p_Result_46_fu_819_p3[44] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd44;
    end else if (p_Result_46_fu_819_p3[45] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd45;
    end else if (p_Result_46_fu_819_p3[46] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd46;
    end else if (p_Result_46_fu_819_p3[47] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd47;
    end else if (p_Result_46_fu_819_p3[48] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd48;
    end else if (p_Result_46_fu_819_p3[49] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd49;
    end else if (p_Result_46_fu_819_p3[50] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd50;
    end else if (p_Result_46_fu_819_p3[51] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd51;
    end else if (p_Result_46_fu_819_p3[52] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd52;
    end else if (p_Result_46_fu_819_p3[53] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd53;
    end else if (p_Result_46_fu_819_p3[54] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd54;
    end else if (p_Result_46_fu_819_p3[55] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd55;
    end else if (p_Result_46_fu_819_p3[56] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd56;
    end else if (p_Result_46_fu_819_p3[57] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd57;
    end else if (p_Result_46_fu_819_p3[58] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd58;
    end else if (p_Result_46_fu_819_p3[59] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd59;
    end else if (p_Result_46_fu_819_p3[60] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd60;
    end else if (p_Result_46_fu_819_p3[61] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd61;
    end else if (p_Result_46_fu_819_p3[62] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd62;
    end else if (p_Result_46_fu_819_p3[63] == 1'b1) begin
        tmp_8_fu_827_p3 = 64'd63;
    end else begin
        tmp_8_fu_827_p3 = 64'd64;
    end
end

assign tmp_fu_386_p4 = {{ret_18_reg_1003[63:52]}};

assign trunc_ln1010_fu_835_p1 = tmp_8_fu_827_p3[31:0];

assign trunc_ln345_fu_542_p1 = p_Result_43_fu_536_p2[52:0];

assign trunc_ln368_fu_375_p1 = add_ln461_fu_363_p2[5:0];

assign trunc_ln628_fu_319_p1 = p_Result_35_fu_301_p5[51:0];

assign trunc_ln645_1_fu_855_p1 = i_V_1_reg_165[10:0];

assign trunc_ln645_2_fu_859_p1 = iy_V_fu_849_p2[10:0];

assign trunc_ln645_fu_651_p1 = i_V_1_reg_165[11:0];

assign trunc_ln646_fu_845_p1 = tmp_8_fu_827_p3[11:0];

assign trunc_ln836_1_fu_956_p1 = ap_mx_2_V_fu_942_p2[51:0];

assign trunc_ln836_fu_953_p1 = r_4_reg_1200[51:0];

assign xor_ln345_fu_530_p2 = (lshr_ln345_fu_524_p2 ^ 54'd9007199254740991);

assign xor_ln832_1_fu_742_p2 = (icmp_ln832_3_fu_683_p2 ^ 1'd1);

assign xor_ln832_fu_703_p2 = (icmp_ln832_2_fu_660_p2 ^ 1'd1);

assign zext_ln1451_1_fu_883_p1 = lshr_ln_fu_874_p4;

assign zext_ln1451_fu_887_p1 = add_ln534_fu_839_p2;

assign zext_ln169_1_fu_417_p1 = p_Result_41_fu_412_p2;

assign zext_ln169_fu_257_p1 = ret_10_fu_225_p4;

assign zext_ln345_fu_520_p1 = sub_ln345_fu_515_p2;

assign zext_ln368_1_fu_450_p1 = select_ln368_1_fu_432_p3;

assign zext_ln368_2_fu_454_p1 = select_ln368_fu_426_p3;

assign zext_ln368_3_fu_458_p1 = select_ln368_2_fu_443_p3;

assign zext_ln368_fu_556_p1 = ap_mx_V_reg_136;

assign zext_ln628_fu_403_p1 = LZ_V_reg_1066;

assign zext_ln803_fu_939_p1 = n_V_reg_1217;

always @ (posedge ap_clk) begin
    zext_ln169_reg_1037[11] <= 1'b0;
    LZ_V_cast_reg_1072[6] <= 1'b0;
end

endmodule //computeP2_generic_remainder_double_s
