# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/SHAKE_Saber/SHAKE_Saber.srcs/sources_1/ip/BRAM64/BRAM64.xci
# IP: The module: 'BRAM64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/SHAKE_Saber/SHAKE_Saber.srcs/sources_1/ip/BRAM64/BRAM64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/SHAKE_Saber/SHAKE_Saber.srcs/sources_1/ip/BRAM64/BRAM64.xci
# IP: The module: 'BRAM64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/SHAKE_Saber/SHAKE_Saber.srcs/sources_1/ip/BRAM64/BRAM64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
