#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 31 15:22:36 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim blk_mem_gen_0_1_tb_behav -key {Behavioral:sim_1:Functional:blk_mem_gen_0_1_tb} -tclbatch blk_mem_gen_0_1_tb.tcl -log simulate.log"
xsim blk_mem_gen_0_1_tb_behav -key {Behavioral:sim_1:Functional:blk_mem_gen_0_1_tb} -tclbatch blk_mem_gen_0_1_tb.tcl -log simulate.log

