#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 12 20:12:41 CET 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Mayo_sign_no_zynq_tb_behav -key {Behavioral:sim_1:Functional:Mayo_sign_no_zynq_tb} -tclbatch Mayo_sign_no_zynq_tb.tcl -protoinst "protoinst_files/Mayo_sign.protoinst" -view /home/osm/Documents/Sect/SECT-MAYO/MAYO/vivado/hw-mayo/Mayo_sign_no_zynq_tb_behav.wcfg -log simulate.log"
xsim Mayo_sign_no_zynq_tb_behav -key {Behavioral:sim_1:Functional:Mayo_sign_no_zynq_tb} -tclbatch Mayo_sign_no_zynq_tb.tcl -protoinst "protoinst_files/Mayo_sign.protoinst" -view /home/osm/Documents/Sect/SECT-MAYO/MAYO/vivado/hw-mayo/Mayo_sign_no_zynq_tb_behav.wcfg -log simulate.log

