# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Mayo_keygen_wrapper.xdc

# Block Designs: bd/Mayo_keygen/Mayo_keygen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen || ORIG_REF_NAME==Mayo_keygen} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_processing_system7_0_0/Mayo_keygen_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_processing_system7_0_0 || ORIG_REF_NAME==Mayo_keygen_processing_system7_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_xbar_0/Mayo_keygen_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_xbar_0 || ORIG_REF_NAME==Mayo_keygen_xbar_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_ps7_0_axi_periph_0/Mayo_keygen_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_ps7_0_axi_periph_0 || ORIG_REF_NAME==Mayo_keygen_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_rst_ps7_0_100M_0/Mayo_keygen_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_rst_ps7_0_100M_0 || ORIG_REF_NAME==Mayo_keygen_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_axi_bram_ctrl_0_1/Mayo_keygen_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_axi_bram_ctrl_0_1 || ORIG_REF_NAME==Mayo_keygen_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_blk_mem_gen_0_2/Mayo_keygen_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_blk_mem_gen_0_2 || ORIG_REF_NAME==Mayo_keygen_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_BIG_BRAM256KDP_0/Mayo_keygen_BIG_BRAM256KDP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_BIG_BRAM256KDP_0 || ORIG_REF_NAME==Mayo_keygen_BIG_BRAM256KDP_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_arbit_brama1_0/Mayo_keygen_arbit_brama1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_arbit_brama1_0 || ORIG_REF_NAME==Mayo_keygen_arbit_brama1_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_Small_BRAM8k_0/Mayo_keygen_Small_BRAM8k_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_Small_BRAM8k_0 || ORIG_REF_NAME==Mayo_keygen_Small_BRAM8k_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_arbit_brama0_0/Mayo_keygen_arbit_brama0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_arbit_brama0_0 || ORIG_REF_NAME==Mayo_keygen_arbit_brama0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_arbit_bramb0_0/Mayo_keygen_arbit_bramb0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_arbit_bramb0_0 || ORIG_REF_NAME==Mayo_keygen_arbit_bramb0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_Ground0_2/Mayo_keygen_Ground0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_Ground0_2 || ORIG_REF_NAME==Mayo_keygen_Ground0_2} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_Ground32_0/Mayo_keygen_Ground32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_Ground32_0 || ORIG_REF_NAME==Mayo_keygen_Ground32_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_Ground4_0/Mayo_keygen_Ground4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_Ground4_0 || ORIG_REF_NAME==Mayo_keygen_Ground4_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_TRNG_0_0/Mayo_keygen_TRNG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_TRNG_0_0 || ORIG_REF_NAME==Mayo_keygen_TRNG_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_trng_arbiter_0_0/Mayo_keygen_mayo_trng_arbiter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_trng_arbiter_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_trng_arbiter_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_MAYO_SHAKE_1_0/Mayo_keygen_MAYO_SHAKE_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_MAYO_SHAKE_1_0 || ORIG_REF_NAME==Mayo_keygen_MAYO_SHAKE_1_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_hash_bram_arbit_0_0/Mayo_keygen_mayo_hash_bram_arbit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_hash_bram_arbit_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_hash_bram_arbit_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_xlconcat_0_0/Mayo_keygen_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_xlconcat_0_0 || ORIG_REF_NAME==Mayo_keygen_xlconcat_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_axi_litev3_0_0/Mayo_keygen_mayo_axi_litev3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_axi_litev3_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_axi_litev3_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_add_vectors_0_0/Mayo_keygen_mayo_add_vectors_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_add_vectors_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_add_vectors_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_linear_combinat_0_0/Mayo_keygen_mayo_linear_combinat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_linear_combinat_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_linear_combinat_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_negate_0_0/Mayo_keygen_mayo_negate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_negate_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_negate_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_reduce_0_0/Mayo_keygen_mayo_reduce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_reduce_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_reduce_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_mayo_sample_oil_space_0_0/Mayo_keygen_mayo_sample_oil_space_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_mayo_sample_oil_space_0_0 || ORIG_REF_NAME==Mayo_keygen_mayo_sample_oil_space_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_MAYO_KEYGEN_FSM_0_0/Mayo_keygen_MAYO_KEYGEN_FSM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_MAYO_KEYGEN_FSM_0_0 || ORIG_REF_NAME==Mayo_keygen_MAYO_KEYGEN_FSM_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_blink_led_0_0/Mayo_keygen_blink_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_blink_led_0_0 || ORIG_REF_NAME==Mayo_keygen_blink_led_0_0} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_auto_pc_1/Mayo_keygen_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_auto_pc_1 || ORIG_REF_NAME==Mayo_keygen_auto_pc_1} -quiet] -quiet

# IP: bd/Mayo_keygen/ip/Mayo_keygen_auto_pc_0/Mayo_keygen_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_keygen_auto_pc_0 || ORIG_REF_NAME==Mayo_keygen_auto_pc_0} -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/Mayo_keygen_ooc.xdc
