webtalk_init -webtalk_dir /home/osm/Documents/SECT-MAYO/MAYO/vivado/test_neoTRNG/test_neoTRNG.sim/sim_1/behav/xsim/xsim.dir/neoTRNG_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 31 20:10:38 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212242419_0_0_600" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "163079bd-e1a8-4576-a7d2-0501e1d5aef5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f117a162473d4419a1844db85271a86c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 11 (bullseye)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2319.308 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119204_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3004071677 -regid "212242419_0_0_600" -xml /home/osm/Documents/SECT-MAYO/MAYO/vivado/test_neoTRNG/test_neoTRNG.sim/sim_1/behav/xsim/xsim.dir/neoTRNG_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/osm/Documents/SECT-MAYO/MAYO/vivado/test_neoTRNG/test_neoTRNG.sim/sim_1/behav/xsim/xsim.dir/neoTRNG_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/osm/Documents/SECT-MAYO/MAYO/vivado/test_neoTRNG/test_neoTRNG.sim/sim_1/behav/xsim/xsim.dir/neoTRNG_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
