#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 02 01:31:01 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ee0609dad2574a6bb453d9688122e31f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot TRNG_tb_behav work.TRNG_tb work.glbl -log elaborate.log"
xelab -wto ee0609dad2574a6bb453d9688122e31f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot TRNG_tb_behav work.TRNG_tb work.glbl -log elaborate.log

