# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.srcs/sources_1/ip/Test_BRAM0/Test_BRAM0.xci
# IP: The module: 'Test_BRAM0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/ip/Test_BRAM0/Test_BRAM0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_BRAM0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.srcs/sources_1/ip/Test_BRAM0/Test_BRAM0.xci
# IP: The module: 'Test_BRAM0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/ip/Test_BRAM0/Test_BRAM0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_BRAM0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
