# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Mayo_keygen_wrapper.xdc

# Block Designs: bd/Mayo_sign/Mayo_sign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign || ORIG_REF_NAME==Mayo_sign} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_Ground0_0/Mayo_sign_Ground0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_Ground0_0 || ORIG_REF_NAME==Mayo_sign_Ground0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_Ground32_0/Mayo_sign_Ground32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_Ground32_0 || ORIG_REF_NAME==Mayo_sign_Ground32_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_Ground4_0/Mayo_sign_Ground4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_Ground4_0 || ORIG_REF_NAME==Mayo_sign_Ground4_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_TRNG_0_0/Mayo_sign_TRNG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_TRNG_0_0 || ORIG_REF_NAME==Mayo_sign_TRNG_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_xlconcat_0_0/Mayo_sign_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_xlconcat_0_0 || ORIG_REF_NAME==Mayo_sign_xlconcat_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_trng_arbiter_0_0/Mayo_sign_mayo_trng_arbiter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_trng_arbiter_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_trng_arbiter_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_MAYO_SHAKE_1_0/Mayo_sign_MAYO_SHAKE_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_MAYO_SHAKE_1_0 || ORIG_REF_NAME==Mayo_sign_MAYO_SHAKE_1_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_hash_bram_arbit_0_0/Mayo_sign_mayo_hash_bram_arbit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_hash_bram_arbit_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_hash_bram_arbit_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_0_0/Mayo_sign_mayo_bram_arbiter2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_0_1/Mayo_sign_mayo_bram_arbiter2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_1 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_1} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_0_2/Mayo_sign_mayo_bram_arbiter2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_2 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_2} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_1_0/Mayo_sign_mayo_bram_arbiter2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_1_0 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_1_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_lin_comb_arbiter_0_0/Mayo_sign_mayo_lin_comb_arbiter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_lin_comb_arbiter_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_lin_comb_arbiter_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_linear_combinat_0_0/Mayo_sign_mayo_linear_combinat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_linear_combinat_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_linear_combinat_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_0_3/Mayo_sign_mayo_bram_arbiter2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_3 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_3} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_bram_arbiter2_0_4/Mayo_sign_mayo_bram_arbiter2_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_4 || ORIG_REF_NAME==Mayo_sign_mayo_bram_arbiter2_0_4} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_add_vectors_0_0/Mayo_sign_mayo_add_vectors_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_add_vectors_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_add_vectors_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_add_vectors_arb_0_0_1/Mayo_sign_mayo_add_vectors_arb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_add_vectors_arb_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_add_vectors_arb_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_MAYO_P1P1T_0_0/Mayo_sign_MAYO_P1P1T_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_MAYO_P1P1T_0_0 || ORIG_REF_NAME==Mayo_sign_MAYO_P1P1T_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_MAYO_SIGNING_FSM_0_0/Mayo_sign_MAYO_SIGNING_FSM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_MAYO_SIGNING_FSM_0_0 || ORIG_REF_NAME==Mayo_sign_MAYO_SIGNING_FSM_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_add_oil_0_0/Mayo_sign_mayo_add_oil_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_add_oil_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_add_oil_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_negate_0_0/Mayo_sign_mayo_negate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_negate_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_negate_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_reduce_0_0/Mayo_sign_mayo_reduce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_reduce_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_reduce_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_reduce_extension_0_0/Mayo_sign_mayo_reduce_extension_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_reduce_extension_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_reduce_extension_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_sample_oil_0_0/Mayo_sign_mayo_sample_oil_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_sample_oil_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_sample_oil_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_sample_oil_space_0_0/Mayo_sign_mayo_sample_oil_space_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_sample_oil_space_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_sample_oil_space_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_mayo_sample_vinegar_0_0/Mayo_sign_mayo_sample_vinegar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_mayo_sample_vinegar_0_0 || ORIG_REF_NAME==Mayo_sign_mayo_sample_vinegar_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_memcpy_0_0/Mayo_sign_memcpy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_memcpy_0_0 || ORIG_REF_NAME==Mayo_sign_memcpy_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_memcpy_0_1/Mayo_sign_memcpy_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_memcpy_0_1 || ORIG_REF_NAME==Mayo_sign_memcpy_0_1} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_tdp_SmallBRAM_1_0_0/Mayo_sign_tdp_SmallBRAM_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_tdp_SmallBRAM_1_0_0 || ORIG_REF_NAME==Mayo_sign_tdp_SmallBRAM_1_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_tdp_BigBRAM_2_0_0/Mayo_sign_tdp_BigBRAM_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_tdp_BigBRAM_2_0_0 || ORIG_REF_NAME==Mayo_sign_tdp_BigBRAM_2_0_0} -quiet] -quiet

# IP: bd/Mayo_sign/ip/Mayo_sign_tdp_BigBRAM_2_0_1/Mayo_sign_tdp_BigBRAM_2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_tdp_BigBRAM_2_0_1 || ORIG_REF_NAME==Mayo_sign_tdp_BigBRAM_2_0_1} -quiet] -quiet

# XDC: /home/osm/Documents/Sect/SECT-MAYO/MAYO/vivado/hw-mayo/hw-mayo.gen/sources_1/bd/Mayo_sign/Mayo_sign_ooc.xdc
