# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Mayo_keygen_wrapper.xdc

# Block Designs: bd/Mayo_sign_with_zynq/Mayo_sign_with_zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq || ORIG_REF_NAME==Mayo_sign_with_zynq} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground0_0/Mayo_sign_with_zynq_Ground0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_Ground0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_Ground0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_processing_system7_0_0/Mayo_sign_with_zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_processing_system7_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_axi_litev3_0_0/Mayo_sign_with_zynq_mayo_axi_litev3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_axi_litev3_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_axi_litev3_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xbar_0/Mayo_sign_with_zynq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_xbar_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_xbar_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_ps7_0_axi_periph_0/Mayo_sign_with_zynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_rst_ps7_0_100M_0/Mayo_sign_with_zynq_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_rst_ps7_0_100M_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconcat_0_1/Mayo_sign_with_zynq_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_xlconcat_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_xlconcat_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconstant_0_0/Mayo_sign_with_zynq_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_xlconstant_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_xlconstant_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_3/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_3 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_3} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_tdp_BigBRAM_2_0_0/Mayo_sign_with_zynq_tdp_BigBRAM_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_tdp_BigBRAM_2_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_tdp_BigBRAM_2_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_4/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_b_4 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_b_4} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_4/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_4 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_4} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_tdp_BigBRAM_3_0_0/Mayo_sign_with_zynq_tdp_BigBRAM_3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_tdp_BigBRAM_3_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_tdp_BigBRAM_3_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground0_1/Mayo_sign_with_zynq_Ground0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_Ground0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_Ground0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground32_1/Mayo_sign_with_zynq_Ground32_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_Ground32_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_Ground32_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_Ground4_1/Mayo_sign_with_zynq_Ground4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_Ground4_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_Ground4_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_1/Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_lin_comb_arbiter_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_linear_combinat_0_1/Mayo_sign_with_zynq_mayo_linear_combinat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_linear_combinat_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_linear_combinat_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_MAYO_P1P1T_0_1/Mayo_sign_with_zynq_MAYO_P1P1T_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_MAYO_P1P1T_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_MAYO_P1P1T_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_1/Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_MAYO_SIGNING_FSM_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_5/Mayo_sign_with_zynq_mayo_bram_arbiter2_a_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_5 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_a_5} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_5/Mayo_sign_with_zynq_mayo_bram_arbiter2_b_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_b_5 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_bram_arbiter2_b_5} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_tdp_SmallBRAM_1_0_0/Mayo_sign_with_zynq_tdp_SmallBRAM_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_tdp_SmallBRAM_1_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_tdp_SmallBRAM_1_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconcat_0_2/Mayo_sign_with_zynq_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_xlconcat_0_2 || ORIG_REF_NAME==Mayo_sign_with_zynq_xlconcat_0_2} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_trng_arbiter_0_1/Mayo_sign_with_zynq_mayo_trng_arbiter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_trng_arbiter_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_trng_arbiter_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_aes_128_ctr_0_0/Mayo_sign_with_zynq_aes_128_ctr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_aes_128_ctr_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_aes_128_ctr_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_vectors_0_1/Mayo_sign_with_zynq_mayo_add_vectors_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_add_vectors_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_add_vectors_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_vectors_arb_0_1/Mayo_sign_with_zynq_mayo_add_vectors_arb_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_add_vectors_arb_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_add_vectors_arb_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_1/Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_hash_bram_arbit_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_xlconstant_0_1/Mayo_sign_with_zynq_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_xlconstant_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_xlconstant_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_shake_128_0_0/Mayo_sign_with_zynq_shake_128_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_shake_128_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_shake_128_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_add_oil_0_1/Mayo_sign_with_zynq_mayo_add_oil_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_add_oil_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_add_oil_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_negate_0_1/Mayo_sign_with_zynq_mayo_negate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_negate_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_negate_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_reduce_0_1/Mayo_sign_with_zynq_mayo_reduce_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_reduce_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_reduce_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_reduce_extension_0_1/Mayo_sign_with_zynq_mayo_reduce_extension_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_reduce_extension_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_reduce_extension_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_oil_0_1/Mayo_sign_with_zynq_mayo_sample_oil_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_sample_oil_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_sample_oil_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_oil_space_0_1/Mayo_sign_with_zynq_mayo_sample_oil_space_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_sample_oil_space_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_sample_oil_space_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_memcpy_0_1/Mayo_sign_with_zynq_memcpy_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_memcpy_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_memcpy_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_memcpy_1_1/Mayo_sign_with_zynq_memcpy_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_memcpy_1_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_memcpy_1_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_axi_bram_ctrl_0_0/Mayo_sign_with_zynq_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_mayo_sample_vinegar_0_1/Mayo_sign_with_zynq_mayo_sample_vinegar_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_mayo_sample_vinegar_0_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_mayo_sample_vinegar_0_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_auto_pc_1/Mayo_sign_with_zynq_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_auto_pc_1 || ORIG_REF_NAME==Mayo_sign_with_zynq_auto_pc_1} -quiet] -quiet

# IP: bd/Mayo_sign_with_zynq/ip/Mayo_sign_with_zynq_auto_pc_0/Mayo_sign_with_zynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mayo_sign_with_zynq_auto_pc_0 || ORIG_REF_NAME==Mayo_sign_with_zynq_auto_pc_0} -quiet] -quiet

# XDC: /home/osm/Documents/Sect/SECT-MAYO/MAYO/vivado/hw-mayo/hw-mayo.gen/sources_1/bd/Mayo_sign_with_zynq/Mayo_sign_with_zynq_ooc.xdc
