#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Aug 04 15:36:22 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim accum_tb_func_impl -key {Post-Implementation:sim_1:Functional:accum_tb} -tclbatch accum_tb.tcl -log simulate.log"
xsim accum_tb_func_impl -key {Post-Implementation:sim_1:Functional:accum_tb} -tclbatch accum_tb.tcl -log simulate.log

