// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="computeP2_computeP2,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.007750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=2683,HLS_SYN_LUT=4525,HLS_VERSION=2020_2}" *)

module computeP2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        oil_space,
        P1,
        P2_i,
        P2_o,
        P2_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 42'd1;
parameter    ap_ST_fsm_state2 = 42'd2;
parameter    ap_ST_fsm_state3 = 42'd4;
parameter    ap_ST_fsm_state4 = 42'd8;
parameter    ap_ST_fsm_state5 = 42'd16;
parameter    ap_ST_fsm_state6 = 42'd32;
parameter    ap_ST_fsm_state7 = 42'd64;
parameter    ap_ST_fsm_state8 = 42'd128;
parameter    ap_ST_fsm_state9 = 42'd256;
parameter    ap_ST_fsm_state10 = 42'd512;
parameter    ap_ST_fsm_state11 = 42'd1024;
parameter    ap_ST_fsm_state12 = 42'd2048;
parameter    ap_ST_fsm_state13 = 42'd4096;
parameter    ap_ST_fsm_state14 = 42'd8192;
parameter    ap_ST_fsm_state15 = 42'd16384;
parameter    ap_ST_fsm_state16 = 42'd32768;
parameter    ap_ST_fsm_state17 = 42'd65536;
parameter    ap_ST_fsm_state18 = 42'd131072;
parameter    ap_ST_fsm_state19 = 42'd262144;
parameter    ap_ST_fsm_state20 = 42'd524288;
parameter    ap_ST_fsm_state21 = 42'd1048576;
parameter    ap_ST_fsm_state22 = 42'd2097152;
parameter    ap_ST_fsm_state23 = 42'd4194304;
parameter    ap_ST_fsm_state24 = 42'd8388608;
parameter    ap_ST_fsm_state25 = 42'd16777216;
parameter    ap_ST_fsm_state26 = 42'd33554432;
parameter    ap_ST_fsm_state27 = 42'd67108864;
parameter    ap_ST_fsm_state28 = 42'd134217728;
parameter    ap_ST_fsm_state29 = 42'd268435456;
parameter    ap_ST_fsm_state30 = 42'd536870912;
parameter    ap_ST_fsm_state31 = 42'd1073741824;
parameter    ap_ST_fsm_state32 = 42'd2147483648;
parameter    ap_ST_fsm_state33 = 42'd4294967296;
parameter    ap_ST_fsm_state34 = 42'd8589934592;
parameter    ap_ST_fsm_state35 = 42'd17179869184;
parameter    ap_ST_fsm_state36 = 42'd34359738368;
parameter    ap_ST_fsm_state37 = 42'd68719476736;
parameter    ap_ST_fsm_state38 = 42'd137438953472;
parameter    ap_ST_fsm_state39 = 42'd274877906944;
parameter    ap_ST_fsm_state40 = 42'd549755813888;
parameter    ap_ST_fsm_state41 = 42'd1099511627776;
parameter    ap_ST_fsm_state42 = 42'd2199023255552;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] oil_space;
input  [7:0] P1;
input  [7:0] P2_i;
output  [7:0] P2_o;
output   P2_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] P2_o;
reg P2_o_ap_vld;

(* fsm_encoding = "none" *) reg   [41:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] grp_remainder_fu_553_ap_return;
reg   [5:0] reg_563;
wire    ap_CS_fsm_state8;
wire    grp_remainder_fu_553_ap_ready;
wire    grp_remainder_fu_553_ap_done;
wire    grp_remainder_fu_558_ap_ready;
wire    grp_remainder_fu_558_ap_done;
reg    ap_block_state8_on_subcall_done;
wire    ap_CS_fsm_state9;
reg    ap_block_state9_on_subcall_done;
wire    ap_CS_fsm_state16;
reg    ap_block_state16_on_subcall_done;
wire    ap_CS_fsm_state17;
reg    ap_block_state17_on_subcall_done;
wire   [5:0] grp_remainder_fu_558_ap_return;
reg   [5:0] reg_568;
wire   [5:0] add_ln19_fu_573_p2;
reg   [5:0] add_ln19_reg_1544;
wire    ap_CS_fsm_state2;
wire   [9:0] empty_46_fu_609_p2;
reg   [9:0] empty_46_reg_1552;
wire   [0:0] icmp_ln19_fu_579_p2;
wire   [5:0] sub_ln28_fu_615_p2;
reg   [5:0] sub_ln28_reg_1557;
wire   [8:0] zext_ln34_fu_621_p1;
reg   [8:0] zext_ln34_reg_1562;
wire   [2:0] add_ln23_fu_624_p2;
reg   [2:0] add_ln23_reg_1570;
wire    ap_CS_fsm_state3;
wire   [14:0] sub_ln29_fu_669_p2;
reg   [14:0] sub_ln29_reg_1578;
wire   [0:0] icmp_ln23_fu_634_p2;
wire   [5:0] add_ln122_fu_690_p2;
reg   [5:0] add_ln122_reg_1589;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln122_fu_684_p2;
reg   [14:0] temp_addr_reg_1594;
reg   [14:0] temp_addr_1_reg_1604;
wire   [8:0] tmp_fu_747_p2;
reg   [8:0] tmp_reg_1614;
wire    ap_CS_fsm_state6;
wire   [8:0] tmp_10_fu_769_p2;
reg   [8:0] tmp_10_reg_1619;
reg   [14:0] temp_addr_2_reg_1624;
reg   [14:0] temp_addr_3_reg_1634;
wire   [8:0] tmp_11_fu_841_p2;
reg   [8:0] tmp_11_reg_1644;
wire    ap_CS_fsm_state7;
wire   [8:0] tmp_16_fu_863_p2;
reg   [8:0] tmp_16_reg_1649;
wire   [5:0] add_ln34_fu_869_p2;
reg   [5:0] add_ln34_reg_1654;
wire    ap_CS_fsm_state11;
wire   [9:0] empty_50_fu_905_p2;
reg   [9:0] empty_50_reg_1662;
wire   [0:0] icmp_ln34_fu_875_p2;
wire   [2:0] add_ln38_fu_911_p2;
reg   [2:0] add_ln38_reg_1667;
wire    ap_CS_fsm_state12;
wire   [14:0] sub_ln41_fu_956_p2;
reg   [14:0] sub_ln41_reg_1675;
wire   [0:0] icmp_ln38_fu_921_p2;
wire   [5:0] add_ln122_1_fu_972_p2;
reg   [5:0] add_ln122_1_reg_1686;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln122_1_fu_966_p2;
reg   [14:0] temp_addr_4_reg_1691;
reg   [14:0] temp_addr_5_reg_1696;
wire   [8:0] tmp_17_fu_1016_p2;
reg   [8:0] tmp_17_reg_1701;
wire    ap_CS_fsm_state14;
wire   [8:0] tmp_18_fu_1029_p2;
reg   [8:0] tmp_18_reg_1706;
reg   [14:0] temp_addr_6_reg_1711;
reg   [14:0] temp_addr_7_reg_1716;
wire   [8:0] tmp_19_fu_1082_p2;
reg   [8:0] tmp_19_reg_1721;
wire    ap_CS_fsm_state15;
wire   [8:0] tmp_20_fu_1095_p2;
reg   [8:0] tmp_20_reg_1726;
wire   [14:0] empty_54_fu_1100_p2;
wire    ap_CS_fsm_state19;
wire   [2:0] add_ln48_fu_1117_p2;
reg   [2:0] add_ln48_reg_1739;
wire    ap_CS_fsm_state20;
wire   [9:0] zext_ln48_fu_1123_p1;
reg   [9:0] zext_ln48_reg_1744;
wire   [9:0] empty_57_fu_1157_p2;
reg   [9:0] empty_57_reg_1752;
wire   [0:0] icmp_ln48_fu_1127_p2;
wire   [5:0] add_ln52_fu_1163_p2;
reg   [5:0] add_ln52_reg_1757;
wire    ap_CS_fsm_state21;
wire   [14:0] sub_ln55_fu_1208_p2;
reg   [14:0] sub_ln55_reg_1765;
wire   [0:0] icmp_ln52_fu_1173_p2;
wire   [14:0] sub_ln55_2_fu_1273_p2;
reg   [14:0] sub_ln55_2_reg_1770;
wire   [5:0] empty_59_fu_1279_p2;
reg   [5:0] empty_59_reg_1775;
wire    ap_CS_fsm_state22;
wire   [0:0] exitcond426_fu_1289_p2;
wire   [14:0] add_ptr523_sum_fu_1305_p2;
reg   [14:0] add_ptr523_sum_reg_1788;
wire   [2:0] add_ln60_fu_1314_p2;
reg   [2:0] add_ln60_reg_1793;
wire    ap_CS_fsm_state24;
wire   [14:0] add_ln60_1_fu_1320_p2;
reg   [14:0] add_ln60_1_reg_1798;
wire   [63:0] zext_ln60_fu_1326_p1;
reg   [63:0] zext_ln60_reg_1803;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln64_fu_1336_p2;
wire   [0:0] icmp_ln69_fu_1346_p2;
reg   [0:0] icmp_ln69_reg_1820;
wire  signed [14:0] grp_fu_1524_p2;
reg   [14:0] mul_ln67_reg_1824;
wire    ap_CS_fsm_state28;
wire   [5:0] empty_64_fu_1351_p2;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire   [5:0] add_ln122_2_fu_1379_p2;
reg   [5:0] add_ln122_2_reg_1845;
wire    ap_CS_fsm_state32;
wire   [0:0] icmp_ln122_2_fu_1373_p2;
wire   [63:0] add_ln64_fu_1385_p2;
wire   [8:0] tmp_21_fu_1403_p2;
reg   [8:0] tmp_21_reg_1860;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
wire   [8:0] tmp_22_fu_1436_p2;
reg   [8:0] tmp_22_reg_1870;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state36;
wire   [8:0] tmp_23_fu_1469_p2;
reg   [8:0] tmp_23_reg_1880;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire   [8:0] tmp_24_fu_1502_p2;
reg   [8:0] tmp_24_reg_1890;
wire    ap_CS_fsm_state39;
wire  signed [7:0] sext_ln122_fu_1508_p1;
wire    ap_CS_fsm_state41;
wire   [10:0] add_ln85_fu_1518_p2;
wire    ap_CS_fsm_state42;
wire   [0:0] icmp_ln85_fu_1512_p2;
reg   [14:0] temp_address0;
reg    temp_ce0;
reg    temp_we0;
wire   [5:0] temp_q0;
reg   [14:0] temp_address1;
reg    temp_ce1;
reg    temp_we1;
wire   [5:0] temp_q1;
reg   [5:0] vec_1_address0;
reg    vec_1_ce0;
reg    vec_1_we0;
wire   [5:0] vec_1_q0;
reg   [5:0] vec_1_address1;
reg    vec_1_ce1;
wire   [5:0] vec_1_q1;
reg   [14:0] tempt_address0;
reg    tempt_ce0;
reg    tempt_we0;
reg   [5:0] tempt_d0;
wire   [5:0] tempt_q0;
reg   [5:0] vec_address0;
reg    vec_ce0;
reg    vec_we0;
reg   [5:0] vec_d0;
wire   [5:0] vec_q0;
wire    grp_linear_combination_fu_527_ap_start;
wire    grp_linear_combination_fu_527_ap_done;
wire    grp_linear_combination_fu_527_ap_idle;
wire    grp_linear_combination_fu_527_ap_ready;
wire   [5:0] grp_linear_combination_fu_527_out_r_address0;
wire    grp_linear_combination_fu_527_out_r_ce0;
wire    grp_linear_combination_fu_527_out_r_we0;
wire   [5:0] grp_linear_combination_fu_527_out_r_d0;
wire    grp_linear_combination_2_fu_535_ap_start;
wire    grp_linear_combination_2_fu_535_ap_done;
wire    grp_linear_combination_2_fu_535_ap_idle;
wire    grp_linear_combination_2_fu_535_ap_ready;
wire   [14:0] grp_linear_combination_2_fu_535_vecs_address0;
wire    grp_linear_combination_2_fu_535_vecs_ce0;
wire   [5:0] grp_linear_combination_2_fu_535_out_r_address0;
wire    grp_linear_combination_2_fu_535_out_r_ce0;
wire    grp_linear_combination_2_fu_535_out_r_we0;
wire   [5:0] grp_linear_combination_2_fu_535_out_r_d0;
wire    grp_linear_combination_1_fu_544_ap_start;
wire    grp_linear_combination_1_fu_544_ap_done;
wire    grp_linear_combination_1_fu_544_ap_idle;
wire    grp_linear_combination_1_fu_544_ap_ready;
wire   [7:0] grp_linear_combination_1_fu_544_out_r;
wire    grp_linear_combination_1_fu_544_out_r_ap_vld;
wire   [14:0] grp_linear_combination_1_fu_544_vecs_address0;
wire    grp_linear_combination_1_fu_544_vecs_ce0;
wire    grp_remainder_fu_553_ap_start;
wire    grp_remainder_fu_553_ap_idle;
reg   [8:0] grp_remainder_fu_553_x;
wire    grp_remainder_fu_558_ap_start;
wire    grp_remainder_fu_558_ap_idle;
reg   [8:0] grp_remainder_fu_558_x;
reg   [5:0] i_reg_337;
reg   [2:0] j_reg_348;
reg   [5:0] i_6_reg_359;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state4;
reg   [5:0] i_4_reg_371;
reg   [2:0] j_1_reg_382;
reg   [5:0] i_8_reg_393;
wire    ap_CS_fsm_state18;
reg   [14:0] empty_53_reg_405;
wire   [0:0] exitcond5511_fu_1111_p2;
reg   [2:0] i_5_reg_416;
reg   [5:0] j_3_reg_427;
reg   [5:0] loop_index_reg_438;
wire    ap_CS_fsm_state23;
reg   [2:0] i_11_reg_449;
reg   [14:0] phi_mul_reg_460;
reg   [63:0] j_4_reg_472;
wire   [0:0] icmp_ln60_fu_1330_p2;
reg   [5:0] empty_63_reg_482;
wire   [0:0] exitcond2_fu_1362_p2;
wire    ap_CS_fsm_state29;
reg   [7:0] v1_0_i_reg_493;
reg   [5:0] i_10_reg_504;
reg   [10:0] i_7_reg_516;
reg    grp_linear_combination_fu_527_ap_start_reg;
reg    grp_linear_combination_2_fu_535_ap_start_reg;
reg    grp_linear_combination_1_fu_544_ap_start_reg;
reg    grp_remainder_fu_553_ap_start_reg;
wire    ap_CS_fsm_state40;
reg    grp_remainder_fu_558_ap_start_reg;
wire   [63:0] zext_ln124_fu_701_p1;
wire   [63:0] zext_ln122_fu_675_p1;
wire   [63:0] zext_ln124_5_fu_726_p1;
wire   [63:0] zext_ln124_3_fu_712_p1;
wire   [63:0] zext_ln124_10_fu_795_p1;
wire   [63:0] zext_ln124_8_fu_781_p1;
wire   [63:0] zext_ln124_15_fu_820_p1;
wire   [63:0] zext_ln124_13_fu_806_p1;
wire   [63:0] zext_ln124_18_fu_983_p1;
wire   [63:0] zext_ln124_21_fu_1003_p1;
wire   [63:0] zext_ln124_24_fu_1049_p1;
wire   [63:0] zext_ln124_27_fu_1069_p1;
wire   [63:0] p_cast_fu_1106_p1;
wire   [63:0] add_ptr584_sum_cast_fu_1300_p1;
wire   [63:0] add_ptr523_sum_cast_fu_1310_p1;
wire   [63:0] p_cast18_fu_1357_p1;
wire   [63:0] zext_ln122_3_fu_1368_p1;
wire   [63:0] zext_ln124_31_fu_1415_p1;
wire   [63:0] zext_ln124_34_fu_1448_p1;
wire   [63:0] zext_ln124_37_fu_1481_p1;
wire   [8:0] p_shl_fu_585_p3;
wire   [6:0] p_shl1_fu_597_p3;
wire   [9:0] p_shl_cast_fu_593_p1;
wire   [9:0] p_shl14_cast_fu_605_p1;
wire   [9:0] zext_ln23_fu_630_p1;
wire   [9:0] add_ln29_fu_640_p2;
wire   [8:0] trunc_ln29_fu_645_p1;
wire   [11:0] shl_ln29_1_fu_657_p3;
wire   [14:0] shl_ln_fu_649_p3;
wire  signed [14:0] sext_ln29_fu_665_p1;
wire   [14:0] zext_ln122_1_fu_680_p1;
wire   [14:0] add_ln124_fu_696_p2;
wire   [5:0] or_ln122_fu_706_p2;
wire   [14:0] zext_ln124_4_fu_717_p1;
wire   [14:0] add_ln124_2_fu_721_p2;
wire  signed [5:0] sext_ln124_fu_731_p0;
wire  signed [7:0] sext_ln124_fu_731_p1;
wire  signed [7:0] sext_ln124_1_fu_739_p1;
wire   [8:0] zext_ln124_2_fu_743_p1;
wire   [8:0] zext_ln124_1_fu_735_p1;
wire  signed [5:0] sext_ln124_2_fu_753_p0;
wire  signed [7:0] sext_ln124_2_fu_753_p1;
wire  signed [7:0] sext_ln124_3_fu_761_p1;
wire   [8:0] zext_ln124_7_fu_765_p1;
wire   [8:0] zext_ln124_6_fu_757_p1;
wire   [5:0] or_ln122_1_fu_775_p2;
wire   [14:0] zext_ln124_9_fu_786_p1;
wire   [14:0] add_ln124_4_fu_790_p2;
wire   [5:0] or_ln122_2_fu_800_p2;
wire   [14:0] zext_ln124_14_fu_811_p1;
wire   [14:0] add_ln124_6_fu_815_p2;
wire  signed [5:0] sext_ln124_4_fu_825_p0;
wire  signed [7:0] sext_ln124_4_fu_825_p1;
wire  signed [7:0] sext_ln124_5_fu_833_p1;
wire   [8:0] zext_ln124_12_fu_837_p1;
wire   [8:0] zext_ln124_11_fu_829_p1;
wire  signed [5:0] sext_ln124_6_fu_847_p0;
wire  signed [7:0] sext_ln124_6_fu_847_p1;
wire  signed [7:0] sext_ln124_7_fu_855_p1;
wire   [8:0] zext_ln124_17_fu_859_p1;
wire   [8:0] zext_ln124_16_fu_851_p1;
wire   [8:0] p_shl2_fu_881_p3;
wire   [6:0] p_shl3_fu_893_p3;
wire   [9:0] p_shl17_cast_fu_889_p1;
wire   [9:0] p_shl18_cast_fu_901_p1;
wire   [9:0] zext_ln38_fu_917_p1;
wire   [9:0] add_ln41_fu_927_p2;
wire   [8:0] trunc_ln41_fu_932_p1;
wire   [11:0] shl_ln41_1_fu_944_p3;
wire   [14:0] shl_ln1_fu_936_p3;
wire  signed [14:0] sext_ln41_fu_952_p1;
wire   [14:0] zext_ln122_2_fu_962_p1;
wire   [14:0] add_ln124_8_fu_978_p2;
wire   [5:0] or_ln122_3_fu_988_p2;
wire   [14:0] zext_ln124_20_fu_994_p1;
wire   [14:0] add_ln124_10_fu_998_p2;
wire  signed [5:0] sext_ln124_8_fu_1008_p0;
wire  signed [7:0] sext_ln124_8_fu_1008_p1;
wire   [8:0] zext_ln124_19_fu_1012_p1;
wire  signed [5:0] sext_ln124_9_fu_1021_p0;
wire  signed [7:0] sext_ln124_9_fu_1021_p1;
wire   [8:0] zext_ln124_22_fu_1025_p1;
wire   [5:0] or_ln122_4_fu_1034_p2;
wire   [14:0] zext_ln124_23_fu_1040_p1;
wire   [14:0] add_ln124_12_fu_1044_p2;
wire   [5:0] or_ln122_5_fu_1054_p2;
wire   [14:0] zext_ln124_26_fu_1060_p1;
wire   [14:0] add_ln124_14_fu_1064_p2;
wire  signed [5:0] sext_ln124_10_fu_1074_p0;
wire  signed [7:0] sext_ln124_10_fu_1074_p1;
wire   [8:0] zext_ln124_25_fu_1078_p1;
wire  signed [5:0] sext_ln124_11_fu_1087_p0;
wire  signed [7:0] sext_ln124_11_fu_1087_p1;
wire   [8:0] zext_ln124_28_fu_1091_p1;
wire   [8:0] p_shl4_fu_1133_p3;
wire   [5:0] p_shl5_fu_1145_p3;
wire   [9:0] p_shl21_cast_fu_1141_p1;
wire   [9:0] p_shl22_cast_fu_1153_p1;
wire   [9:0] zext_ln52_fu_1169_p1;
wire   [9:0] add_ln55_fu_1179_p2;
wire   [8:0] trunc_ln55_fu_1184_p1;
wire   [11:0] shl_ln55_1_fu_1196_p3;
wire   [14:0] shl_ln2_fu_1188_p3;
wire  signed [14:0] sext_ln55_fu_1204_p1;
wire   [8:0] shl_ln55_2_fu_1214_p3;
wire   [6:0] shl_ln55_3_fu_1226_p3;
wire   [9:0] zext_ln55_fu_1222_p1;
wire   [9:0] zext_ln55_1_fu_1234_p1;
wire   [9:0] sub_ln55_1_fu_1238_p2;
wire   [9:0] add_ln55_1_fu_1244_p2;
wire   [8:0] trunc_ln55_1_fu_1249_p1;
wire   [11:0] shl_ln55_5_fu_1261_p3;
wire   [14:0] shl_ln55_4_fu_1253_p3;
wire  signed [14:0] sext_ln55_1_fu_1269_p1;
wire   [14:0] loop_index_cast_fu_1285_p1;
wire   [14:0] add_ptr584_sum_fu_1295_p2;
wire  signed [7:0] sext_ln124_12_fu_1395_p1;
wire   [8:0] zext_ln124_30_fu_1399_p1;
wire   [8:0] zext_ln124_29_fu_1391_p1;
wire   [5:0] or_ln122_6_fu_1409_p2;
wire  signed [7:0] sext_ln124_13_fu_1420_p1;
wire  signed [7:0] sext_ln124_14_fu_1428_p1;
wire   [8:0] zext_ln124_32_fu_1424_p1;
wire   [8:0] zext_ln124_33_fu_1432_p1;
wire   [5:0] or_ln122_7_fu_1442_p2;
wire  signed [7:0] sext_ln124_15_fu_1453_p1;
wire  signed [7:0] sext_ln124_16_fu_1461_p1;
wire   [8:0] zext_ln124_35_fu_1457_p1;
wire   [8:0] zext_ln124_36_fu_1465_p1;
wire   [5:0] or_ln122_8_fu_1475_p2;
wire  signed [7:0] sext_ln124_17_fu_1486_p1;
wire  signed [7:0] sext_ln124_18_fu_1494_p1;
wire   [8:0] zext_ln124_38_fu_1490_p1;
wire   [8:0] zext_ln124_39_fu_1498_p1;
wire  signed [14:0] grp_fu_1524_p0;
wire   [12:0] grp_fu_1524_p1;
reg   [41:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 42'd1;
#0 grp_linear_combination_fu_527_ap_start_reg = 1'b0;
#0 grp_linear_combination_2_fu_535_ap_start_reg = 1'b0;
#0 grp_linear_combination_1_fu_544_ap_start_reg = 1'b0;
#0 grp_remainder_fu_553_ap_start_reg = 1'b0;
#0 grp_remainder_fu_558_ap_start_reg = 1'b0;
end

computeP2_temp #(
    .DataWidth( 6 ),
    .AddressRange( 20160 ),
    .AddressWidth( 15 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(reg_568),
    .q0(temp_q0),
    .address1(temp_address1),
    .ce1(temp_ce1),
    .we1(temp_we1),
    .d1(reg_563),
    .q1(temp_q1)
);

computeP2_vec_1 #(
    .DataWidth( 6 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
vec_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(vec_1_address0),
    .ce0(vec_1_ce0),
    .we0(vec_1_we0),
    .d0(grp_linear_combination_fu_527_out_r_d0),
    .q0(vec_1_q0),
    .address1(vec_1_address1),
    .ce1(vec_1_ce1),
    .q1(vec_1_q1)
);

computeP2_tempt #(
    .DataWidth( 6 ),
    .AddressRange( 20160 ),
    .AddressWidth( 15 ))
tempt_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tempt_address0),
    .ce0(tempt_ce0),
    .we0(tempt_we0),
    .d0(tempt_d0),
    .q0(tempt_q0)
);

computeP2_vec #(
    .DataWidth( 6 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
vec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(vec_address0),
    .ce0(vec_ce0),
    .we0(vec_we0),
    .d0(vec_d0),
    .q0(vec_q0)
);

computeP2_linear_combination grp_linear_combination_fu_527(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_combination_fu_527_ap_start),
    .ap_done(grp_linear_combination_fu_527_ap_done),
    .ap_idle(grp_linear_combination_fu_527_ap_idle),
    .ap_ready(grp_linear_combination_fu_527_ap_ready),
    .vecs_read(P1),
    .coeffs_read(oil_space),
    .len(sub_ln28_reg_1557),
    .out_r_address0(grp_linear_combination_fu_527_out_r_address0),
    .out_r_ce0(grp_linear_combination_fu_527_out_r_ce0),
    .out_r_we0(grp_linear_combination_fu_527_out_r_we0),
    .out_r_d0(grp_linear_combination_fu_527_out_r_d0)
);

computeP2_linear_combination_2 grp_linear_combination_2_fu_535(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_combination_2_fu_535_ap_start),
    .ap_done(grp_linear_combination_2_fu_535_ap_done),
    .ap_idle(grp_linear_combination_2_fu_535_ap_idle),
    .ap_ready(grp_linear_combination_2_fu_535_ap_ready),
    .coeffs_read(oil_space),
    .vecs_address0(grp_linear_combination_2_fu_535_vecs_address0),
    .vecs_ce0(grp_linear_combination_2_fu_535_vecs_ce0),
    .vecs_q0(tempt_q0),
    .vecs_offset(phi_mul_reg_460),
    .out_r_address0(grp_linear_combination_2_fu_535_out_r_address0),
    .out_r_ce0(grp_linear_combination_2_fu_535_out_r_ce0),
    .out_r_we0(grp_linear_combination_2_fu_535_out_r_we0),
    .out_r_d0(grp_linear_combination_2_fu_535_out_r_d0)
);

computeP2_linear_combination_1 grp_linear_combination_1_fu_544(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_combination_1_fu_544_ap_start),
    .ap_done(grp_linear_combination_1_fu_544_ap_done),
    .ap_idle(grp_linear_combination_1_fu_544_ap_idle),
    .ap_ready(grp_linear_combination_1_fu_544_ap_ready),
    .coeffs_read(oil_space),
    .out_r(grp_linear_combination_1_fu_544_out_r),
    .out_r_ap_vld(grp_linear_combination_1_fu_544_out_r_ap_vld),
    .vecs_address0(grp_linear_combination_1_fu_544_vecs_address0),
    .vecs_ce0(grp_linear_combination_1_fu_544_vecs_ce0),
    .vecs_q0(tempt_q0),
    .vecs_offset(mul_ln67_reg_1824)
);

computeP2_remainder grp_remainder_fu_553(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_remainder_fu_553_ap_start),
    .ap_done(grp_remainder_fu_553_ap_done),
    .ap_idle(grp_remainder_fu_553_ap_idle),
    .ap_ready(grp_remainder_fu_553_ap_ready),
    .x(grp_remainder_fu_553_x),
    .ap_return(grp_remainder_fu_553_ap_return)
);

computeP2_remainder grp_remainder_fu_558(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_remainder_fu_558_ap_start),
    .ap_done(grp_remainder_fu_558_ap_done),
    .ap_idle(grp_remainder_fu_558_ap_idle),
    .ap_ready(grp_remainder_fu_558_ap_ready),
    .x(grp_remainder_fu_558_x),
    .ap_return(grp_remainder_fu_558_ap_return)
);

computeP2_mul_mul_15s_13ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 15 ))
mul_mul_15s_13ns_15_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1524_p0),
    .din1(grp_fu_1524_p1),
    .ce(1'b1),
    .dout(grp_fu_1524_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_combination_1_fu_544_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state28)) begin
            grp_linear_combination_1_fu_544_ap_start_reg <= 1'b1;
        end else if ((grp_linear_combination_1_fu_544_ap_ready == 1'b1)) begin
            grp_linear_combination_1_fu_544_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_combination_2_fu_535_ap_start_reg <= 1'b0;
    end else begin
        if (((exitcond2_fu_1362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
            grp_linear_combination_2_fu_535_ap_start_reg <= 1'b1;
        end else if ((grp_linear_combination_2_fu_535_ap_ready == 1'b1)) begin
            grp_linear_combination_2_fu_535_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_combination_fu_527_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_634_p2 == 1'd0))) begin
            grp_linear_combination_fu_527_ap_start_reg <= 1'b1;
        end else if ((grp_linear_combination_fu_527_ap_ready == 1'b1)) begin
            grp_linear_combination_fu_527_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_remainder_fu_553_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8)) | ((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16)))) begin
            grp_remainder_fu_553_ap_start_reg <= 1'b1;
        end else if ((grp_remainder_fu_553_ap_ready == 1'b1)) begin
            grp_remainder_fu_553_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_remainder_fu_558_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8)) | ((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16)))) begin
            grp_remainder_fu_558_ap_start_reg <= 1'b1;
        end else if ((grp_remainder_fu_558_ap_ready == 1'b1)) begin
            grp_remainder_fu_558_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_fu_875_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_53_reg_405 <= 15'd0;
    end else if (((exitcond5511_fu_1111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        empty_53_reg_405 <= empty_54_fu_1100_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_linear_combination_1_fu_544_ap_done == 1'b1) & (icmp_ln69_reg_1820 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
        empty_63_reg_482 <= 6'd0;
    end else if (((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        empty_63_reg_482 <= empty_64_fu_1351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
        i_10_reg_504 <= add_ln122_2_reg_1845;
    end else if (((grp_linear_combination_2_fu_535_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        i_10_reg_504 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        i_11_reg_449 <= 3'd0;
    end else if (((icmp_ln64_fu_1336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        i_11_reg_449 <= add_ln60_reg_1793;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln19_fu_579_p2 == 1'd1))) begin
        i_4_reg_371 <= 6'd0;
    end else if (((icmp_ln38_fu_921_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        i_4_reg_371 <= add_ln34_reg_1654;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5511_fu_1111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        i_5_reg_416 <= 3'd0;
    end else if (((icmp_ln52_fu_1173_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        i_5_reg_416 <= add_ln48_reg_1739;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_linear_combination_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_6_reg_359 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i_6_reg_359 <= add_ln122_reg_1589;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_fu_1330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_7_reg_516 <= 11'd0;
    end else if (((icmp_ln85_fu_1512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        i_7_reg_516 <= add_ln85_fu_1518_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_921_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i_8_reg_393 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        i_8_reg_393 <= add_ln122_1_reg_1686;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_337 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_634_p2 == 1'd1))) begin
        i_reg_337 <= add_ln19_reg_1544;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_fu_875_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        j_1_reg_382 <= 3'd0;
    end else if (((icmp_ln122_1_fu_966_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        j_1_reg_382 <= add_ln38_reg_1667;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_1127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        j_3_reg_427 <= 6'd0;
    end else if (((exitcond426_fu_1289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        j_3_reg_427 <= add_ln52_reg_1757;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) & ((icmp_ln122_2_fu_1373_p2 == 1'd1) | (icmp_ln69_reg_1820 == 1'd1)))) begin
        j_4_reg_472 <= add_ln64_fu_1385_p2;
    end else if (((icmp_ln60_fu_1330_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        j_4_reg_472 <= zext_ln60_fu_1326_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln19_fu_579_p2 == 1'd0))) begin
        j_reg_348 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln122_fu_684_p2 == 1'd1))) begin
        j_reg_348 <= add_ln23_reg_1570;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        loop_index_reg_438 <= empty_59_reg_1775;
    end else if (((icmp_ln52_fu_1173_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        loop_index_reg_438 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        phi_mul_reg_460 <= 15'd0;
    end else if (((icmp_ln64_fu_1336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        phi_mul_reg_460 <= add_ln60_1_reg_1798;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
        v1_0_i_reg_493 <= sext_ln122_fu_1508_p1;
    end else if (((grp_linear_combination_2_fu_535_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        v1_0_i_reg_493 <= P2_i;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_1_fu_966_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln122_1_reg_1686 <= add_ln122_1_fu_972_p2;
        temp_addr_4_reg_1691 <= zext_ln124_18_fu_983_p1;
        temp_addr_5_reg_1696[14 : 1] <= zext_ln124_21_fu_1003_p1[14 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_2_fu_1373_p2 == 1'd0) & (icmp_ln69_reg_1820 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
        add_ln122_2_reg_1845 <= add_ln122_2_fu_1379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln122_fu_684_p2 == 1'd0))) begin
        add_ln122_reg_1589 <= add_ln122_fu_690_p2;
        temp_addr_1_reg_1604[14 : 1] <= zext_ln124_5_fu_726_p1[14 : 1];
        temp_addr_reg_1594 <= zext_ln124_fu_701_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln19_reg_1544 <= add_ln19_fu_573_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln23_reg_1570 <= add_ln23_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln34_reg_1654 <= add_ln34_fu_869_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln38_reg_1667 <= add_ln38_fu_911_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln48_reg_1739 <= add_ln48_fu_1117_p2;
        zext_ln48_reg_1744[2 : 0] <= zext_ln48_fu_1123_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        add_ln52_reg_1757 <= add_ln52_fu_1163_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln60_1_reg_1798 <= add_ln60_1_fu_1320_p2;
        add_ln60_reg_1793 <= add_ln60_fu_1314_p2;
        zext_ln60_reg_1803[2 : 0] <= zext_ln60_fu_1326_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond426_fu_1289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        add_ptr523_sum_reg_1788 <= add_ptr523_sum_fu_1305_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln19_fu_579_p2 == 1'd0))) begin
        empty_46_reg_1552[9 : 1] <= empty_46_fu_609_p2[9 : 1];
        sub_ln28_reg_1557 <= sub_ln28_fu_615_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_fu_875_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_50_reg_1662[9 : 1] <= empty_50_fu_905_p2[9 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln48_fu_1127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        empty_57_reg_1752[9 : 3] <= empty_57_fu_1157_p2[9 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        empty_59_reg_1775 <= empty_59_fu_1279_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_fu_1336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        icmp_ln69_reg_1820 <= icmp_ln69_fu_1346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        mul_ln67_reg_1824 <= grp_fu_1524_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8)) | ((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17)) | ((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16)))) begin
        reg_563 <= grp_remainder_fu_553_ap_return;
        reg_568 <= grp_remainder_fu_558_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_634_p2 == 1'd0))) begin
        sub_ln29_reg_1578[14 : 2] <= sub_ln29_fu_669_p2[14 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_921_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        sub_ln41_reg_1675[14 : 2] <= sub_ln41_fu_956_p2[14 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_1173_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        sub_ln55_2_reg_1770[14 : 2] <= sub_ln55_2_fu_1273_p2[14 : 2];
        sub_ln55_reg_1765[14 : 2] <= sub_ln55_fu_1208_p2[14 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_addr_2_reg_1624 <= zext_ln124_10_fu_795_p1;
        temp_addr_3_reg_1634[14 : 2] <= zext_ln124_15_fu_820_p1[14 : 2];
        tmp_10_reg_1619 <= tmp_10_fu_769_p2;
        tmp_reg_1614 <= tmp_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_addr_6_reg_1711 <= zext_ln124_24_fu_1049_p1;
        temp_addr_7_reg_1716[14 : 2] <= zext_ln124_27_fu_1069_p1[14 : 2];
        tmp_17_reg_1701 <= tmp_17_fu_1016_p2;
        tmp_18_reg_1706 <= tmp_18_fu_1029_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_11_reg_1644 <= tmp_11_fu_841_p2;
        tmp_16_reg_1649 <= tmp_16_fu_863_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_19_reg_1721 <= tmp_19_fu_1082_p2;
        tmp_20_reg_1726 <= tmp_20_fu_1095_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        tmp_21_reg_1860 <= tmp_21_fu_1403_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        tmp_22_reg_1870 <= tmp_22_fu_1436_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        tmp_23_reg_1880 <= tmp_23_fu_1469_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        tmp_24_reg_1890 <= tmp_24_fu_1502_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln19_fu_579_p2 == 1'd1))) begin
        zext_ln34_reg_1562[7 : 0] <= zext_ln34_fu_621_p1[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_1512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        P2_o = 8'd0;
    end else if (((icmp_ln122_2_fu_1373_p2 == 1'd1) & (icmp_ln69_reg_1820 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
        P2_o = v1_0_i_reg_493;
    end else if (((grp_linear_combination_1_fu_544_out_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        P2_o = grp_linear_combination_1_fu_544_out_r;
    end else begin
        P2_o = P2_i;
    end
end

always @ (*) begin
    if ((((icmp_ln85_fu_1512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42)) | ((icmp_ln122_2_fu_1373_p2 == 1'd1) & (icmp_ln69_reg_1820 == 1'd0) & (1'b1 == ap_CS_fsm_state32)))) begin
        P2_o_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        P2_o_ap_vld = grp_linear_combination_1_fu_544_out_r_ap_vld;
    end else begin
        P2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_1512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_1512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_remainder_fu_553_x = tmp_24_reg_1890;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_remainder_fu_553_x = tmp_23_reg_1880;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_remainder_fu_553_x = tmp_22_reg_1870;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_remainder_fu_553_x = tmp_21_reg_1860;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_remainder_fu_553_x = tmp_19_reg_1721;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_remainder_fu_553_x = tmp_17_reg_1701;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_remainder_fu_553_x = tmp_11_reg_1644;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_remainder_fu_553_x = tmp_reg_1614;
    end else begin
        grp_remainder_fu_553_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_remainder_fu_558_x = tmp_20_reg_1726;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_remainder_fu_558_x = tmp_18_reg_1706;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_remainder_fu_558_x = tmp_16_reg_1649;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_remainder_fu_558_x = tmp_10_reg_1619;
    end else begin
        grp_remainder_fu_558_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        temp_address0 = add_ptr584_sum_cast_fu_1300_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_address0 = temp_addr_7_reg_1716;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_address0 = temp_addr_5_reg_1696;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_address0 = zext_ln124_27_fu_1069_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        temp_address0 = zext_ln124_21_fu_1003_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_address0 = temp_addr_3_reg_1634;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_address0 = temp_addr_1_reg_1604;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_address0 = zext_ln124_15_fu_820_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp_address0 = zext_ln124_5_fu_726_p1;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_address1 = temp_addr_6_reg_1711;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_address1 = temp_addr_4_reg_1691;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_address1 = zext_ln124_24_fu_1049_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        temp_address1 = zext_ln124_18_fu_983_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_address1 = temp_addr_2_reg_1624;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_address1 = temp_addr_reg_1594;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_address1 = zext_ln124_10_fu_795_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp_address1 = zext_ln124_fu_701_p1;
    end else begin
        temp_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17)))) begin
        temp_ce0 = 1'b1;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17)))) begin
        temp_ce1 = 1'b1;
    end else begin
        temp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17)))) begin
        temp_we0 = 1'b1;
    end else begin
        temp_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17)))) begin
        temp_we1 = 1'b1;
    end else begin
        temp_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        tempt_address0 = add_ptr523_sum_cast_fu_1310_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        tempt_address0 = p_cast_fu_1106_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        tempt_address0 = grp_linear_combination_1_fu_544_vecs_address0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        tempt_address0 = grp_linear_combination_2_fu_535_vecs_address0;
    end else begin
        tempt_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state19))) begin
        tempt_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        tempt_ce0 = grp_linear_combination_1_fu_544_vecs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        tempt_ce0 = grp_linear_combination_2_fu_535_vecs_ce0;
    end else begin
        tempt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        tempt_d0 = temp_q0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        tempt_d0 = 6'd0;
    end else begin
        tempt_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | ((exitcond5511_fu_1111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        tempt_we0 = 1'b1;
    end else begin
        tempt_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        vec_1_address0 = zext_ln124_13_fu_806_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vec_1_address0 = zext_ln124_3_fu_712_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vec_1_address0 = grp_linear_combination_fu_527_out_r_address0;
    end else begin
        vec_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        vec_1_address1 = zext_ln124_8_fu_781_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vec_1_address1 = zext_ln122_fu_675_p1;
    end else begin
        vec_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        vec_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vec_1_ce0 = grp_linear_combination_fu_527_out_r_ce0;
    end else begin
        vec_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        vec_1_ce1 = 1'b1;
    end else begin
        vec_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        vec_1_we0 = grp_linear_combination_fu_527_out_r_we0;
    end else begin
        vec_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        vec_address0 = zext_ln124_37_fu_1481_p1;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        vec_address0 = zext_ln124_34_fu_1448_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        vec_address0 = zext_ln124_31_fu_1415_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        vec_address0 = zext_ln122_3_fu_1368_p1;
    end else if (((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        vec_address0 = p_cast18_fu_1357_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        vec_address0 = grp_linear_combination_2_fu_535_out_r_address0;
    end else begin
        vec_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state32) | ((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30)))) begin
        vec_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        vec_ce0 = grp_linear_combination_2_fu_535_out_r_ce0;
    end else begin
        vec_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        vec_d0 = 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        vec_d0 = grp_linear_combination_2_fu_535_out_r_d0;
    end else begin
        vec_d0 = 'bx;
    end
end

always @ (*) begin
    if (((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        vec_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        vec_we0 = grp_linear_combination_2_fu_535_out_r_we0;
    end else begin
        vec_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln19_fu_579_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_634_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_linear_combination_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln122_fu_684_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln34_fu_875_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln38_fu_921_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((icmp_ln122_1_fu_966_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state19 : begin
            if (((exitcond5511_fu_1111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln48_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln52_fu_1173_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((exitcond426_fu_1289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln60_fu_1330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln64_fu_1336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_linear_combination_1_fu_544_ap_done == 1'b1) & (icmp_ln69_reg_1820 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else if (((grp_linear_combination_1_fu_544_ap_done == 1'b1) & (icmp_ln69_reg_1820 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((exitcond2_fu_1362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state31 : begin
            if (((grp_linear_combination_2_fu_535_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & ((icmp_ln122_2_fu_1373_p2 == 1'd1) | (icmp_ln69_reg_1820 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((grp_remainder_fu_553_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((icmp_ln85_fu_1512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln122_1_fu_972_p2 = (i_8_reg_393 + 6'd4);

assign add_ln122_2_fu_1379_p2 = (i_10_reg_504 + 6'd4);

assign add_ln122_fu_690_p2 = (i_6_reg_359 + 6'd4);

assign add_ln124_10_fu_998_p2 = (zext_ln124_20_fu_994_p1 + sub_ln41_reg_1675);

assign add_ln124_12_fu_1044_p2 = (zext_ln124_23_fu_1040_p1 + sub_ln41_reg_1675);

assign add_ln124_14_fu_1064_p2 = (zext_ln124_26_fu_1060_p1 + sub_ln41_reg_1675);

assign add_ln124_2_fu_721_p2 = (zext_ln124_4_fu_717_p1 + sub_ln29_reg_1578);

assign add_ln124_4_fu_790_p2 = (zext_ln124_9_fu_786_p1 + sub_ln29_reg_1578);

assign add_ln124_6_fu_815_p2 = (zext_ln124_14_fu_811_p1 + sub_ln29_reg_1578);

assign add_ln124_8_fu_978_p2 = (zext_ln122_2_fu_962_p1 + sub_ln41_reg_1675);

assign add_ln124_fu_696_p2 = (zext_ln122_1_fu_680_p1 + sub_ln29_reg_1578);

assign add_ln19_fu_573_p2 = (i_reg_337 + 6'd1);

assign add_ln23_fu_624_p2 = (j_reg_348 + 3'd1);

assign add_ln29_fu_640_p2 = (zext_ln23_fu_630_p1 + empty_46_reg_1552);

assign add_ln34_fu_869_p2 = (i_4_reg_371 + 6'd1);

assign add_ln38_fu_911_p2 = (j_1_reg_382 + 3'd1);

assign add_ln41_fu_927_p2 = (zext_ln38_fu_917_p1 + empty_50_reg_1662);

assign add_ln48_fu_1117_p2 = (i_5_reg_416 + 3'd1);

assign add_ln52_fu_1163_p2 = (j_3_reg_427 + 6'd1);

assign add_ln55_1_fu_1244_p2 = (sub_ln55_1_fu_1238_p2 + zext_ln48_reg_1744);

assign add_ln55_fu_1179_p2 = (zext_ln52_fu_1169_p1 + empty_57_reg_1752);

assign add_ln60_1_fu_1320_p2 = (phi_mul_reg_460 + 15'd3360);

assign add_ln60_fu_1314_p2 = (i_11_reg_449 + 3'd1);

assign add_ln64_fu_1385_p2 = (j_4_reg_472 + 64'd1);

assign add_ln85_fu_1518_p2 = (i_7_reg_516 + 11'd2);

assign add_ptr523_sum_cast_fu_1310_p1 = add_ptr523_sum_reg_1788;

assign add_ptr523_sum_fu_1305_p2 = (loop_index_cast_fu_1285_p1 + sub_ln55_reg_1765);

assign add_ptr584_sum_cast_fu_1300_p1 = add_ptr584_sum_fu_1295_p2;

assign add_ptr584_sum_fu_1295_p2 = (loop_index_cast_fu_1285_p1 + sub_ln55_2_reg_1770);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state16_on_subcall_done = ((grp_remainder_fu_558_ap_done == 1'b0) | (grp_remainder_fu_553_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state17_on_subcall_done = ((grp_remainder_fu_558_ap_done == 1'b0) | (grp_remainder_fu_553_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_remainder_fu_558_ap_done == 1'b0) | (grp_remainder_fu_553_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state9_on_subcall_done = ((grp_remainder_fu_558_ap_done == 1'b0) | (grp_remainder_fu_553_ap_done == 1'b0));
end

assign empty_46_fu_609_p2 = (p_shl_cast_fu_593_p1 - p_shl14_cast_fu_605_p1);

assign empty_50_fu_905_p2 = (p_shl17_cast_fu_889_p1 - p_shl18_cast_fu_901_p1);

assign empty_54_fu_1100_p2 = (empty_53_reg_405 + 15'd1);

assign empty_57_fu_1157_p2 = (p_shl21_cast_fu_1141_p1 - p_shl22_cast_fu_1153_p1);

assign empty_59_fu_1279_p2 = (loop_index_reg_438 + 6'd1);

assign empty_64_fu_1351_p2 = (empty_63_reg_482 + 6'd1);

assign exitcond2_fu_1362_p2 = ((empty_63_reg_482 == 6'd60) ? 1'b1 : 1'b0);

assign exitcond426_fu_1289_p2 = ((loop_index_reg_438 == 6'd60) ? 1'b1 : 1'b0);

assign exitcond5511_fu_1111_p2 = ((empty_53_reg_405 == 15'd20160) ? 1'b1 : 1'b0);

assign grp_fu_1524_p0 = j_4_reg_472[14:0];

assign grp_fu_1524_p1 = 15'd3360;

assign grp_linear_combination_1_fu_544_ap_start = grp_linear_combination_1_fu_544_ap_start_reg;

assign grp_linear_combination_2_fu_535_ap_start = grp_linear_combination_2_fu_535_ap_start_reg;

assign grp_linear_combination_fu_527_ap_start = grp_linear_combination_fu_527_ap_start_reg;

assign grp_remainder_fu_553_ap_start = grp_remainder_fu_553_ap_start_reg;

assign grp_remainder_fu_558_ap_start = grp_remainder_fu_558_ap_start_reg;

assign icmp_ln122_1_fu_966_p2 = ((i_8_reg_393 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln122_2_fu_1373_p2 = ((i_10_reg_504 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_684_p2 = ((i_6_reg_359 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_579_p2 = ((i_reg_337 == 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_634_p2 = ((j_reg_348 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_875_p2 = ((i_4_reg_371 == 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_921_p2 = ((j_1_reg_382 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_1127_p2 = ((i_5_reg_416 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1173_p2 = ((j_3_reg_427 == 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_1330_p2 = ((i_11_reg_449 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_1336_p2 = ((j_4_reg_472 == 64'd6) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_1346_p2 = ((j_4_reg_472 == zext_ln60_reg_1803) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_1512_p2 = ((i_7_reg_516 < 11'd1260) ? 1'b1 : 1'b0);

assign loop_index_cast_fu_1285_p1 = loop_index_reg_438;

assign or_ln122_1_fu_775_p2 = (i_6_reg_359 | 6'd2);

assign or_ln122_2_fu_800_p2 = (i_6_reg_359 | 6'd3);

assign or_ln122_3_fu_988_p2 = (i_8_reg_393 | 6'd1);

assign or_ln122_4_fu_1034_p2 = (i_8_reg_393 | 6'd2);

assign or_ln122_5_fu_1054_p2 = (i_8_reg_393 | 6'd3);

assign or_ln122_6_fu_1409_p2 = (i_10_reg_504 | 6'd1);

assign or_ln122_7_fu_1442_p2 = (i_10_reg_504 | 6'd2);

assign or_ln122_8_fu_1475_p2 = (i_10_reg_504 | 6'd3);

assign or_ln122_fu_706_p2 = (i_6_reg_359 | 6'd1);

assign p_cast18_fu_1357_p1 = empty_63_reg_482;

assign p_cast_fu_1106_p1 = empty_53_reg_405;

assign p_shl14_cast_fu_605_p1 = p_shl1_fu_597_p3;

assign p_shl17_cast_fu_889_p1 = p_shl2_fu_881_p3;

assign p_shl18_cast_fu_901_p1 = p_shl3_fu_893_p3;

assign p_shl1_fu_597_p3 = {{i_reg_337}, {1'd0}};

assign p_shl21_cast_fu_1141_p1 = p_shl4_fu_1133_p3;

assign p_shl22_cast_fu_1153_p1 = p_shl5_fu_1145_p3;

assign p_shl2_fu_881_p3 = {{i_4_reg_371}, {3'd0}};

assign p_shl3_fu_893_p3 = {{i_4_reg_371}, {1'd0}};

assign p_shl4_fu_1133_p3 = {{i_5_reg_416}, {6'd0}};

assign p_shl5_fu_1145_p3 = {{i_5_reg_416}, {3'd0}};

assign p_shl_cast_fu_593_p1 = p_shl_fu_585_p3;

assign p_shl_fu_585_p3 = {{i_reg_337}, {3'd0}};

assign sext_ln122_fu_1508_p1 = $signed(grp_remainder_fu_553_ap_return);

assign sext_ln124_10_fu_1074_p0 = temp_q1;

assign sext_ln124_10_fu_1074_p1 = sext_ln124_10_fu_1074_p0;

assign sext_ln124_11_fu_1087_p0 = temp_q0;

assign sext_ln124_11_fu_1087_p1 = sext_ln124_11_fu_1087_p0;

assign sext_ln124_12_fu_1395_p1 = $signed(vec_q0);

assign sext_ln124_13_fu_1420_p1 = $signed(grp_remainder_fu_553_ap_return);

assign sext_ln124_14_fu_1428_p1 = $signed(vec_q0);

assign sext_ln124_15_fu_1453_p1 = $signed(grp_remainder_fu_553_ap_return);

assign sext_ln124_16_fu_1461_p1 = $signed(vec_q0);

assign sext_ln124_17_fu_1486_p1 = $signed(grp_remainder_fu_553_ap_return);

assign sext_ln124_18_fu_1494_p1 = $signed(vec_q0);

assign sext_ln124_1_fu_739_p1 = $signed(vec_1_q1);

assign sext_ln124_2_fu_753_p0 = temp_q0;

assign sext_ln124_2_fu_753_p1 = sext_ln124_2_fu_753_p0;

assign sext_ln124_3_fu_761_p1 = $signed(vec_1_q0);

assign sext_ln124_4_fu_825_p0 = temp_q1;

assign sext_ln124_4_fu_825_p1 = sext_ln124_4_fu_825_p0;

assign sext_ln124_5_fu_833_p1 = $signed(vec_1_q1);

assign sext_ln124_6_fu_847_p0 = temp_q0;

assign sext_ln124_6_fu_847_p1 = sext_ln124_6_fu_847_p0;

assign sext_ln124_7_fu_855_p1 = $signed(vec_1_q0);

assign sext_ln124_8_fu_1008_p0 = temp_q1;

assign sext_ln124_8_fu_1008_p1 = sext_ln124_8_fu_1008_p0;

assign sext_ln124_9_fu_1021_p0 = temp_q0;

assign sext_ln124_9_fu_1021_p1 = sext_ln124_9_fu_1021_p0;

assign sext_ln124_fu_731_p0 = temp_q1;

assign sext_ln124_fu_731_p1 = sext_ln124_fu_731_p0;

assign sext_ln29_fu_665_p1 = $signed(shl_ln29_1_fu_657_p3);

assign sext_ln41_fu_952_p1 = $signed(shl_ln41_1_fu_944_p3);

assign sext_ln55_1_fu_1269_p1 = $signed(shl_ln55_5_fu_1261_p3);

assign sext_ln55_fu_1204_p1 = $signed(shl_ln55_1_fu_1196_p3);

assign shl_ln1_fu_936_p3 = {{trunc_ln41_fu_932_p1}, {6'd0}};

assign shl_ln29_1_fu_657_p3 = {{add_ln29_fu_640_p2}, {2'd0}};

assign shl_ln2_fu_1188_p3 = {{trunc_ln55_fu_1184_p1}, {6'd0}};

assign shl_ln41_1_fu_944_p3 = {{add_ln41_fu_927_p2}, {2'd0}};

assign shl_ln55_1_fu_1196_p3 = {{add_ln55_fu_1179_p2}, {2'd0}};

assign shl_ln55_2_fu_1214_p3 = {{j_3_reg_427}, {3'd0}};

assign shl_ln55_3_fu_1226_p3 = {{j_3_reg_427}, {1'd0}};

assign shl_ln55_4_fu_1253_p3 = {{trunc_ln55_1_fu_1249_p1}, {6'd0}};

assign shl_ln55_5_fu_1261_p3 = {{add_ln55_1_fu_1244_p2}, {2'd0}};

assign shl_ln_fu_649_p3 = {{trunc_ln29_fu_645_p1}, {6'd0}};

assign sub_ln28_fu_615_p2 = ($signed(6'd56) - $signed(i_reg_337));

assign sub_ln29_fu_669_p2 = ($signed(shl_ln_fu_649_p3) - $signed(sext_ln29_fu_665_p1));

assign sub_ln41_fu_956_p2 = ($signed(shl_ln1_fu_936_p3) - $signed(sext_ln41_fu_952_p1));

assign sub_ln55_1_fu_1238_p2 = (zext_ln55_fu_1222_p1 - zext_ln55_1_fu_1234_p1);

assign sub_ln55_2_fu_1273_p2 = ($signed(shl_ln55_4_fu_1253_p3) - $signed(sext_ln55_1_fu_1269_p1));

assign sub_ln55_fu_1208_p2 = ($signed(shl_ln2_fu_1188_p3) - $signed(sext_ln55_fu_1204_p1));

assign tmp_10_fu_769_p2 = (zext_ln124_7_fu_765_p1 + zext_ln124_6_fu_757_p1);

assign tmp_11_fu_841_p2 = (zext_ln124_12_fu_837_p1 + zext_ln124_11_fu_829_p1);

assign tmp_16_fu_863_p2 = (zext_ln124_17_fu_859_p1 + zext_ln124_16_fu_851_p1);

assign tmp_17_fu_1016_p2 = (zext_ln124_19_fu_1012_p1 + zext_ln34_reg_1562);

assign tmp_18_fu_1029_p2 = (zext_ln124_22_fu_1025_p1 + zext_ln34_reg_1562);

assign tmp_19_fu_1082_p2 = (zext_ln124_25_fu_1078_p1 + zext_ln34_reg_1562);

assign tmp_20_fu_1095_p2 = (zext_ln124_28_fu_1091_p1 + zext_ln34_reg_1562);

assign tmp_21_fu_1403_p2 = (zext_ln124_30_fu_1399_p1 + zext_ln124_29_fu_1391_p1);

assign tmp_22_fu_1436_p2 = (zext_ln124_32_fu_1424_p1 + zext_ln124_33_fu_1432_p1);

assign tmp_23_fu_1469_p2 = (zext_ln124_35_fu_1457_p1 + zext_ln124_36_fu_1465_p1);

assign tmp_24_fu_1502_p2 = (zext_ln124_38_fu_1490_p1 + zext_ln124_39_fu_1498_p1);

assign tmp_fu_747_p2 = (zext_ln124_2_fu_743_p1 + zext_ln124_1_fu_735_p1);

assign trunc_ln29_fu_645_p1 = add_ln29_fu_640_p2[8:0];

assign trunc_ln41_fu_932_p1 = add_ln41_fu_927_p2[8:0];

assign trunc_ln55_1_fu_1249_p1 = add_ln55_1_fu_1244_p2[8:0];

assign trunc_ln55_fu_1184_p1 = add_ln55_fu_1179_p2[8:0];

assign zext_ln122_1_fu_680_p1 = i_6_reg_359;

assign zext_ln122_2_fu_962_p1 = i_8_reg_393;

assign zext_ln122_3_fu_1368_p1 = i_10_reg_504;

assign zext_ln122_fu_675_p1 = i_6_reg_359;

assign zext_ln124_10_fu_795_p1 = add_ln124_4_fu_790_p2;

assign zext_ln124_11_fu_829_p1 = $unsigned(sext_ln124_4_fu_825_p1);

assign zext_ln124_12_fu_837_p1 = $unsigned(sext_ln124_5_fu_833_p1);

assign zext_ln124_13_fu_806_p1 = or_ln122_2_fu_800_p2;

assign zext_ln124_14_fu_811_p1 = or_ln122_2_fu_800_p2;

assign zext_ln124_15_fu_820_p1 = add_ln124_6_fu_815_p2;

assign zext_ln124_16_fu_851_p1 = $unsigned(sext_ln124_6_fu_847_p1);

assign zext_ln124_17_fu_859_p1 = $unsigned(sext_ln124_7_fu_855_p1);

assign zext_ln124_18_fu_983_p1 = add_ln124_8_fu_978_p2;

assign zext_ln124_19_fu_1012_p1 = $unsigned(sext_ln124_8_fu_1008_p1);

assign zext_ln124_1_fu_735_p1 = $unsigned(sext_ln124_fu_731_p1);

assign zext_ln124_20_fu_994_p1 = or_ln122_3_fu_988_p2;

assign zext_ln124_21_fu_1003_p1 = add_ln124_10_fu_998_p2;

assign zext_ln124_22_fu_1025_p1 = $unsigned(sext_ln124_9_fu_1021_p1);

assign zext_ln124_23_fu_1040_p1 = or_ln122_4_fu_1034_p2;

assign zext_ln124_24_fu_1049_p1 = add_ln124_12_fu_1044_p2;

assign zext_ln124_25_fu_1078_p1 = $unsigned(sext_ln124_10_fu_1074_p1);

assign zext_ln124_26_fu_1060_p1 = or_ln122_5_fu_1054_p2;

assign zext_ln124_27_fu_1069_p1 = add_ln124_14_fu_1064_p2;

assign zext_ln124_28_fu_1091_p1 = $unsigned(sext_ln124_11_fu_1087_p1);

assign zext_ln124_29_fu_1391_p1 = v1_0_i_reg_493;

assign zext_ln124_2_fu_743_p1 = $unsigned(sext_ln124_1_fu_739_p1);

assign zext_ln124_30_fu_1399_p1 = $unsigned(sext_ln124_12_fu_1395_p1);

assign zext_ln124_31_fu_1415_p1 = or_ln122_6_fu_1409_p2;

assign zext_ln124_32_fu_1424_p1 = $unsigned(sext_ln124_13_fu_1420_p1);

assign zext_ln124_33_fu_1432_p1 = $unsigned(sext_ln124_14_fu_1428_p1);

assign zext_ln124_34_fu_1448_p1 = or_ln122_7_fu_1442_p2;

assign zext_ln124_35_fu_1457_p1 = $unsigned(sext_ln124_15_fu_1453_p1);

assign zext_ln124_36_fu_1465_p1 = $unsigned(sext_ln124_16_fu_1461_p1);

assign zext_ln124_37_fu_1481_p1 = or_ln122_8_fu_1475_p2;

assign zext_ln124_38_fu_1490_p1 = $unsigned(sext_ln124_17_fu_1486_p1);

assign zext_ln124_39_fu_1498_p1 = $unsigned(sext_ln124_18_fu_1494_p1);

assign zext_ln124_3_fu_712_p1 = or_ln122_fu_706_p2;

assign zext_ln124_4_fu_717_p1 = or_ln122_fu_706_p2;

assign zext_ln124_5_fu_726_p1 = add_ln124_2_fu_721_p2;

assign zext_ln124_6_fu_757_p1 = $unsigned(sext_ln124_2_fu_753_p1);

assign zext_ln124_7_fu_765_p1 = $unsigned(sext_ln124_3_fu_761_p1);

assign zext_ln124_8_fu_781_p1 = or_ln122_1_fu_775_p2;

assign zext_ln124_9_fu_786_p1 = or_ln122_1_fu_775_p2;

assign zext_ln124_fu_701_p1 = add_ln124_fu_696_p2;

assign zext_ln23_fu_630_p1 = j_reg_348;

assign zext_ln34_fu_621_p1 = P1;

assign zext_ln38_fu_917_p1 = j_1_reg_382;

assign zext_ln48_fu_1123_p1 = i_5_reg_416;

assign zext_ln52_fu_1169_p1 = j_3_reg_427;

assign zext_ln55_1_fu_1234_p1 = shl_ln55_3_fu_1226_p3;

assign zext_ln55_fu_1222_p1 = shl_ln55_2_fu_1214_p3;

assign zext_ln60_fu_1326_p1 = i_11_reg_449;

always @ (posedge ap_clk) begin
    empty_46_reg_1552[0] <= 1'b0;
    zext_ln34_reg_1562[8] <= 1'b0;
    sub_ln29_reg_1578[1:0] <= 2'b00;
    temp_addr_1_reg_1604[0] <= 1'b1;
    temp_addr_3_reg_1634[1:0] <= 2'b11;
    empty_50_reg_1662[0] <= 1'b0;
    sub_ln41_reg_1675[1:0] <= 2'b00;
    temp_addr_5_reg_1696[0] <= 1'b1;
    temp_addr_7_reg_1716[1:0] <= 2'b11;
    zext_ln48_reg_1744[9:3] <= 7'b0000000;
    empty_57_reg_1752[2:0] <= 3'b000;
    sub_ln55_reg_1765[1:0] <= 2'b00;
    sub_ln55_2_reg_1770[1:0] <= 2'b00;
    zext_ln60_reg_1803[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //computeP2
