// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module computeP2_linear_combination_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        oil_space_address0,
        oil_space_ce0,
        oil_space_q0,
        P2_address0,
        P2_ce0,
        P2_we0,
        P2_d0,
        vecs_address0,
        vecs_ce0,
        vecs_q0,
        vecs_offset,
        coeffs,
        out_r
);

parameter    ap_ST_fsm_state1 = 48'd1;
parameter    ap_ST_fsm_state2 = 48'd2;
parameter    ap_ST_fsm_state3 = 48'd4;
parameter    ap_ST_fsm_state4 = 48'd8;
parameter    ap_ST_fsm_state5 = 48'd16;
parameter    ap_ST_fsm_state6 = 48'd32;
parameter    ap_ST_fsm_state7 = 48'd64;
parameter    ap_ST_fsm_state8 = 48'd128;
parameter    ap_ST_fsm_state9 = 48'd256;
parameter    ap_ST_fsm_state10 = 48'd512;
parameter    ap_ST_fsm_state11 = 48'd1024;
parameter    ap_ST_fsm_state12 = 48'd2048;
parameter    ap_ST_fsm_state13 = 48'd4096;
parameter    ap_ST_fsm_state14 = 48'd8192;
parameter    ap_ST_fsm_state15 = 48'd16384;
parameter    ap_ST_fsm_state16 = 48'd32768;
parameter    ap_ST_fsm_state17 = 48'd65536;
parameter    ap_ST_fsm_state18 = 48'd131072;
parameter    ap_ST_fsm_state19 = 48'd262144;
parameter    ap_ST_fsm_state20 = 48'd524288;
parameter    ap_ST_fsm_state21 = 48'd1048576;
parameter    ap_ST_fsm_state22 = 48'd2097152;
parameter    ap_ST_fsm_state23 = 48'd4194304;
parameter    ap_ST_fsm_state24 = 48'd8388608;
parameter    ap_ST_fsm_state25 = 48'd16777216;
parameter    ap_ST_fsm_state26 = 48'd33554432;
parameter    ap_ST_fsm_state27 = 48'd67108864;
parameter    ap_ST_fsm_state28 = 48'd134217728;
parameter    ap_ST_fsm_state29 = 48'd268435456;
parameter    ap_ST_fsm_state30 = 48'd536870912;
parameter    ap_ST_fsm_state31 = 48'd1073741824;
parameter    ap_ST_fsm_state32 = 48'd2147483648;
parameter    ap_ST_fsm_state33 = 48'd4294967296;
parameter    ap_ST_fsm_state34 = 48'd8589934592;
parameter    ap_ST_fsm_state35 = 48'd17179869184;
parameter    ap_ST_fsm_state36 = 48'd34359738368;
parameter    ap_ST_fsm_state37 = 48'd68719476736;
parameter    ap_ST_fsm_state38 = 48'd137438953472;
parameter    ap_ST_fsm_state39 = 48'd274877906944;
parameter    ap_ST_fsm_state40 = 48'd549755813888;
parameter    ap_ST_fsm_state41 = 48'd1099511627776;
parameter    ap_ST_fsm_state42 = 48'd2199023255552;
parameter    ap_ST_fsm_state43 = 48'd4398046511104;
parameter    ap_ST_fsm_state44 = 48'd8796093022208;
parameter    ap_ST_fsm_state45 = 48'd17592186044416;
parameter    ap_ST_fsm_state46 = 48'd35184372088832;
parameter    ap_ST_fsm_state47 = 48'd70368744177664;
parameter    ap_ST_fsm_state48 = 48'd140737488355328;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] oil_space_address0;
output   oil_space_ce0;
input  [7:0] oil_space_q0;
output  [10:0] P2_address0;
output   P2_ce0;
output   P2_we0;
output  [7:0] P2_d0;
output  [14:0] vecs_address0;
output   vecs_ce0;
input  [4:0] vecs_q0;
input  [14:0] vecs_offset;
input  [8:0] coeffs;
input  [10:0] out_r;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg oil_space_ce0;
reg P2_ce0;
reg P2_we0;
reg vecs_ce0;

(* fsm_encoding = "none" *) reg   [47:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] accumulators_q0;
reg   [31:0] reg_193;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state11;
wire   [5:0] empty_25_fu_197_p2;
wire    ap_CS_fsm_state2;
wire   [5:0] add_ln97_fu_214_p2;
reg   [5:0] add_ln97_reg_389;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln97_fu_224_p2;
wire   [14:0] add_ln103_fu_274_p2;
reg   [14:0] add_ln103_reg_402;
wire   [12:0] zext_ln101_fu_279_p1;
reg   [12:0] zext_ln101_reg_407;
wire    ap_CS_fsm_state4;
wire   [5:0] add_ln101_fu_283_p2;
reg   [5:0] add_ln101_reg_412;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln101_fu_298_p2;
reg   [5:0] accumulators_addr_4_reg_425;
wire    ap_CS_fsm_state6;
wire   [5:0] add_ln107_fu_318_p2;
reg   [5:0] add_ln107_reg_435;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln107_fu_333_p2;
wire   [10:0] add_ln111_fu_339_p2;
reg   [10:0] add_ln111_reg_448;
wire   [7:0] grp_fu_344_p2;
reg   [7:0] urem_ln111_reg_453;
wire    ap_CS_fsm_state47;
reg   [5:0] accumulators_address0;
reg    accumulators_ce0;
reg    accumulators_we0;
reg   [31:0] accumulators_d0;
reg   [5:0] empty_reg_149;
wire   [0:0] exitcond136_fu_208_p2;
reg   [5:0] i_reg_160;
reg   [5:0] j_reg_171;
wire    ap_CS_fsm_state9;
reg   [5:0] i_2_reg_182;
wire    ap_CS_fsm_state48;
wire   [63:0] p_cast3_fu_203_p1;
wire   [63:0] p_cast5_fu_269_p1;
wire   [63:0] zext_ln103_fu_309_p1;
wire   [63:0] zext_ln101_3_fu_289_p1;
wire   [63:0] zext_ln107_fu_324_p1;
wire   [63:0] zext_ln111_fu_354_p1;
wire    ap_CS_fsm_state7;
wire   [31:0] grp_fu_358_p3;
wire   [11:0] p_shl_fu_230_p3;
wire   [7:0] p_shl2_fu_242_p3;
wire   [12:0] p_shl_cast_fu_238_p1;
wire   [12:0] p_shl2_cast_fu_250_p1;
wire   [12:0] empty_28_fu_254_p2;
wire   [8:0] zext_ln97_fu_220_p1;
wire   [8:0] empty_29_fu_264_p2;
wire  signed [14:0] p_cast_fu_260_p1;
wire   [14:0] zext_ln101_4_fu_294_p1;
wire   [14:0] add_ln103_3_fu_304_p2;
wire   [10:0] zext_ln107_1_fu_329_p1;
wire   [5:0] grp_fu_344_p1;
wire    ap_CS_fsm_state12;
wire   [4:0] grp_fu_358_p0;
wire   [7:0] grp_fu_358_p1;
reg    grp_fu_344_ap_start;
wire    grp_fu_344_ap_done;
reg   [47:0] ap_NS_fsm;
wire   [12:0] grp_fu_358_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 48'd1;
end

computeP2_linear_combination_accumulators #(
    .DataWidth( 32 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(accumulators_address0),
    .ce0(accumulators_ce0),
    .we0(accumulators_we0),
    .d0(accumulators_d0),
    .q0(accumulators_q0)
);

computeP2_urem_32ns_6ns_8_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
urem_32ns_6ns_8_36_seq_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_344_ap_start),
    .done(grp_fu_344_ap_done),
    .din0(reg_193),
    .din1(grp_fu_344_p1),
    .ce(1'b1),
    .dout(grp_fu_344_p2)
);

computeP2_mac_muladd_5ns_8ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_5ns_8ns_32ns_32_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_358_p0),
    .din1(grp_fu_358_p1),
    .din2(accumulators_q0),
    .ce(1'b1),
    .dout(grp_fu_358_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond136_fu_208_p2 == 1'd0))) begin
        empty_reg_149 <= empty_25_fu_197_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_149 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln97_fu_224_p2 == 1'd1))) begin
        i_2_reg_182 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        i_2_reg_182 <= add_ln107_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond136_fu_208_p2 == 1'd1))) begin
        i_reg_160 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln101_fu_298_p2 == 1'd1))) begin
        i_reg_160 <= add_ln97_reg_389;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_171 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        j_reg_171 <= add_ln101_reg_412;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln101_fu_298_p2 == 1'd0))) begin
        accumulators_addr_4_reg_425 <= zext_ln101_3_fu_289_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln101_reg_412 <= add_ln101_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln97_fu_224_p2 == 1'd0))) begin
        add_ln103_reg_402 <= add_ln103_fu_274_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln107_reg_435 <= add_ln107_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln107_fu_333_p2 == 1'd0))) begin
        add_ln111_reg_448 <= add_ln111_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln97_reg_389 <= add_ln97_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_193 <= accumulators_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        urem_ln111_reg_453 <= grp_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        zext_ln101_reg_407[7 : 0] <= zext_ln101_fu_279_p1[7 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        P2_ce0 = 1'b1;
    end else begin
        P2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        P2_we0 = 1'b1;
    end else begin
        P2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        accumulators_address0 = zext_ln107_fu_324_p1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        accumulators_address0 = accumulators_addr_4_reg_425;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        accumulators_address0 = p_cast3_fu_203_p1;
    end else begin
        accumulators_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state2))) begin
        accumulators_ce0 = 1'b1;
    end else begin
        accumulators_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        accumulators_d0 = grp_fu_358_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        accumulators_d0 = 32'd0;
    end else begin
        accumulators_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state2) & (exitcond136_fu_208_p2 == 1'd0)))) begin
        accumulators_we0 = 1'b1;
    end else begin
        accumulators_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln107_fu_333_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln107_fu_333_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_344_ap_start = 1'b1;
    end else begin
        grp_fu_344_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        oil_space_ce0 = 1'b1;
    end else begin
        oil_space_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        vecs_ce0 = 1'b1;
    end else begin
        vecs_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond136_fu_208_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln97_fu_224_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln101_fu_298_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln107_fu_333_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P2_address0 = zext_ln111_fu_354_p1;

assign P2_d0 = urem_ln111_reg_453[7:0];

assign add_ln101_fu_283_p2 = (j_reg_171 + 6'd1);

assign add_ln103_3_fu_304_p2 = (add_ln103_reg_402 + zext_ln101_4_fu_294_p1);

assign add_ln103_fu_274_p2 = ($signed(p_cast_fu_260_p1) + $signed(vecs_offset));

assign add_ln107_fu_318_p2 = (i_2_reg_182 + 6'd1);

assign add_ln111_fu_339_p2 = (zext_ln107_1_fu_329_p1 + out_r);

assign add_ln97_fu_214_p2 = (i_reg_160 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign empty_25_fu_197_p2 = (empty_reg_149 + 6'd1);

assign empty_28_fu_254_p2 = (p_shl_cast_fu_238_p1 - p_shl2_cast_fu_250_p1);

assign empty_29_fu_264_p2 = (zext_ln97_fu_220_p1 + coeffs);

assign exitcond136_fu_208_p2 = ((empty_reg_149 == 6'd60) ? 1'b1 : 1'b0);

assign grp_fu_344_p1 = 32'd31;

assign grp_fu_358_p0 = grp_fu_358_p00;

assign grp_fu_358_p00 = vecs_q0;

assign grp_fu_358_p1 = zext_ln101_reg_407;

assign icmp_ln101_fu_298_p2 = ((j_reg_171 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_333_p2 = ((i_2_reg_182 == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_224_p2 = ((i_reg_160 == 6'd56) ? 1'b1 : 1'b0);

assign oil_space_address0 = p_cast5_fu_269_p1;

assign p_cast3_fu_203_p1 = empty_reg_149;

assign p_cast5_fu_269_p1 = empty_29_fu_264_p2;

assign p_cast_fu_260_p1 = $signed(empty_28_fu_254_p2);

assign p_shl2_cast_fu_250_p1 = p_shl2_fu_242_p3;

assign p_shl2_fu_242_p3 = {{i_reg_160}, {2'd0}};

assign p_shl_cast_fu_238_p1 = p_shl_fu_230_p3;

assign p_shl_fu_230_p3 = {{i_reg_160}, {6'd0}};

assign vecs_address0 = zext_ln103_fu_309_p1;

assign zext_ln101_3_fu_289_p1 = j_reg_171;

assign zext_ln101_4_fu_294_p1 = j_reg_171;

assign zext_ln101_fu_279_p1 = oil_space_q0;

assign zext_ln103_fu_309_p1 = add_ln103_3_fu_304_p2;

assign zext_ln107_1_fu_329_p1 = i_2_reg_182;

assign zext_ln107_fu_324_p1 = i_2_reg_182;

assign zext_ln111_fu_354_p1 = add_ln111_reg_448;

assign zext_ln97_fu_220_p1 = i_reg_160;

always @ (posedge ap_clk) begin
    zext_ln101_reg_407[12:8] <= 5'b00000;
end

endmodule //computeP2_linear_combination_1
