#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jul 25 16:24:16 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto a572b227f0ba45d18a695388a9a92fe8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot shake128_tb_behav xil_defaultlib.shake128_tb -log elaborate.log"
xelab -wto a572b227f0ba45d18a695388a9a92fe8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot shake128_tb_behav xil_defaultlib.shake128_tb -log elaborate.log

