#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 22 20:21:30 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim shake128_tb_behav -key {Behavioral:sim_1:Functional:shake128_tb} -tclbatch shake128_tb.tcl -log simulate.log"
xsim shake128_tb_behav -key {Behavioral:sim_1:Functional:shake128_tb} -tclbatch shake128_tb.tcl -log simulate.log

