#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 25 17:08:26 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto fcb7daa5fb9c48cd9eb124f3de52bf7a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot neoTRNG_tb_behav xil_defaultlib.neoTRNG_tb -log elaborate.log"
xelab -wto fcb7daa5fb9c48cd9eb124f3de52bf7a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot neoTRNG_tb_behav xil_defaultlib.neoTRNG_tb -log elaborate.log

