webtalk_init -webtalk_dir /home/osm/Documents/SECT-MAYO/TRNG_project/TRNG_project.sim/sim_1/behav/xsim/xsim.dir/TRNG_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 11 18:46:51 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212242419_0_0_600" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "163079bd-e1a8-4576-a7d2-0501e1d5aef5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ee0609dad2574a6bb453d9688122e31f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "105" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 11 (bullseye)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2077.532 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20243800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.79_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3295039671 -regid "212242419_0_0_600" -xml /home/osm/Documents/SECT-MAYO/TRNG_project/TRNG_project.sim/sim_1/behav/xsim/xsim.dir/TRNG_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/osm/Documents/SECT-MAYO/TRNG_project/TRNG_project.sim/sim_1/behav/xsim/xsim.dir/TRNG_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/osm/Documents/SECT-MAYO/TRNG_project/TRNG_project.sim/sim_1/behav/xsim/xsim.dir/TRNG_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
