#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Aug 01 20:24:26 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim adder_tb_func_synth -key {Post-Synthesis:sim_1:Functional:adder_tb} -tclbatch adder_tb.tcl -log simulate.log"
xsim adder_tb_func_synth -key {Post-Synthesis:sim_1:Functional:adder_tb} -tclbatch adder_tb.tcl -log simulate.log

