#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 24 22:48:26 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim add_oil_tb_behav -key {Behavioral:sim_1:Functional:add_oil_tb} -tclbatch add_oil_tb.tcl -protoinst "protoinst_files/bd_882c.protoinst" -view /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/Mayo_keygen_no_zynq_tb_behav.wcfg -log simulate.log"
xsim add_oil_tb_behav -key {Behavioral:sim_1:Functional:add_oil_tb} -tclbatch add_oil_tb.tcl -protoinst "protoinst_files/bd_882c.protoinst" -view /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/Mayo_keygen_no_zynq_tb_behav.wcfg -log simulate.log

