#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 08 15:31:57 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim core_env_tb_behav -key {Behavioral:sim_1:Functional:core_env_tb} -tclbatch core_env_tb.tcl -protoinst "protoinst_files/Mayo_keygen_no_zynq.protoinst" -protoinst "protoinst_files/Mayo_keygen.protoinst" -view /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/Mayo_keygen_no_zynq_tb_behav.wcfg -log simulate.log"
xsim core_env_tb_behav -key {Behavioral:sim_1:Functional:core_env_tb} -tclbatch core_env_tb.tcl -protoinst "protoinst_files/Mayo_keygen_no_zynq.protoinst" -protoinst "protoinst_files/Mayo_keygen.protoinst" -view /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/Mayo_keygen_no_zynq_tb_behav.wcfg -log simulate.log

