# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.srcs/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/Mayo_keygen_system_ila_0_3.xci
# IP: The module: 'Mayo_keygen_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/bd_882c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882c || ORIG_REF_NAME==bd_882c} -quiet] -quiet

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/bd_882c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/bd_882c_ila_lib_0_ooc.xdc

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/bd_882c_ooc.xdc

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/Mayo_keygen_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mayo_keygen_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.srcs/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/Mayo_keygen_system_ila_0_3.xci
# IP: The module: 'Mayo_keygen_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/bd_882c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882c || ORIG_REF_NAME==bd_882c} -quiet] -quiet

# IP: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/bd_882c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_882c_ila_lib_0 || ORIG_REF_NAME==bd_882c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/ip/ip_0/bd_882c_ila_lib_0_ooc.xdc

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/bd_0/bd_882c_ooc.xdc

# XDC: /home/osm/Documents/SECT-MAYO/MAYO/vivado/MAYO_KeyGen_v2/MAYO_KeyGen_v2.gen/sources_1/bd/Mayo_keygen/ip/Mayo_keygen_system_ila_0_3/Mayo_keygen_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mayo_keygen_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
